- platform: "mqtt"
  name: "ikea_plug_1"
  state_topic: "zigbee2mqtt/ikea_plug_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_1/set"

- platform: "mqtt"
  name: "ikea_plug_5"
  state_topic: "zigbee2mqtt/ikea_plug_5"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_5/set"

- platform: "mqtt"
  name: "ikea_plug_7"
  state_topic: "zigbee2mqtt/ikea_plug_7"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_7/set"

- platform: "mqtt"
  name: "ikea_plug_8"
  state_topic: "zigbee2mqtt/ikea_plug_8"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_8/set"

- platform: "mqtt"
  name: "ikea_plug_3"
  state_topic: "zigbee2mqtt/ikea_plug_3"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_3/set"

- platform: "mqtt"
  name: "ikea_plug_2"
  state_topic: "zigbee2mqtt/ikea_plug_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_2/set"

- platform: "mqtt"
  name: "ikea_plug_4"
  state_topic: "zigbee2mqtt/ikea_plug_4"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state }}"
  command_topic: "zigbee2mqtt/ikea_plug_4/set"

