- platform: "mqtt"
  name: "xiaomi_relay_1_l1"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state_l1 }}"
  command_topic: "zigbee2mqtt/xiaomi_relay_1/l1/set"

- platform: "mqtt"
  name: "xiaomi_relay_1_l2"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  payload_off: "OFF"
  payload_on: "ON"
  value_template: "{{ value_json.state_l2 }}"
  command_topic: "zigbee2mqtt/xiaomi_relay_1/l2/set"
