title: "Settings"
id: settings
cards:
- type: vertical-stack
  cards:
  - type: entities
    show_header_toggle: false
    entities:
    - input_boolean.vacation_mode
  - type: conditional
    conditions:
    - entity: input_boolean.vacation_mode
      state: "on"
    card: 
      type: entities
      show_header_toggle: false
      entities:
      - script.vacation_lights
      - automation.vacation_lights_start_on_sunset
      - automation.vacation_lights_stop_at_midnight

- type: entities
  show_header_toggle: false
  entities:
  - input_boolean.logger_deconz
  - input_boolean.logger_mqtt
  - input_boolean.logger_python_script
  - input_boolean.logger_shell_commands
  - input_boolean.logger_helpers_script

- type: entities
  show_header_toggle: false
  entities:
  - input_boolean.guestroom_blinds_auto
