# https://www.home-assistant.io/components/alarm_control_panel.manual/
#
# DISARMED -> pedning -> ARMED -> pending + delay -> TRIGGERED -> DISARMED
#                                            |-> DISARMED 
#
- platform: manual
  name: House
  code: !secret alarm_code
  pending_time: 0
  delay_time: 0
  trigger_time: 180
  disarm_after_trigger: true
  armed_home:
    pending_time: 0
    delay_time: 0
    trigger_time: 60
  armed_away:
    pending_time: 60
    delay_time: 5
    trigger_time: 180
