# https://www.home-assistant.io/components/alarm_control_panel.manual/
#
# DISARMED -> arming -> ARMED -> pending -> TRIGGERED -> DISARMED
#                                            |-> DISARMED 
#
- platform: manual
  name: House
  code: !secret alarm_code
  disarm_after_trigger: false
  disarmed:
    trigger_time: 0
  armed_home:
    arming_time: 0
    delay_time: 0
    trigger_time: 60
  armed_away:
    arming_time: 60
    delay_time: 60
    trigger_time: 300
  armed_night:
    arming_time: 0
    delay_time: 40
    trigger_time: 300
