# https://www.home-assistant.io/components/alarm_control_panel.manual/
#
# DISARMED -> pedning -> ARMED -> pending + delay -> TRIGGERED -> DISARMED
#                                            |-> DISARMED 
#
- platform: manual
  name: House
  code: !secret alarm_code
  disarm_after_trigger: false
  disarmed:
    trigger_time: 0
  armed_home:
    pending_time: 0
    delay_time: 0
    trigger_time: 60
  armed_away:
    delay_time: 0
    pending_time: 60
    trigger_time: 300
