- platform: generic
  name: Weather
  still_image_url: !secret yr_url_weather_location
  content_type: 'image/svg+xml'


- platform: foscam
  name: Foscam 1
  ip: !secret foscam1_ip
  username: !secret foscam1_username
  password: !secret foscam1_password

- platform: foscam
  name: Foscam 2
  ip: !secret foscam2_ip
  username: !secret foscam2_username
  password: !secret foscam2_password
