- platform: generic
  name: Weather
  still_image_url: !secret yr_url_weather_location
  content_type: 'image/svg+xml'


- platform: foscam
  name: Foscam 1
  ip: !secret foscam1_ip
  username: !secret foscam1_username
  password: !secret foscam1_password

- platform: foscam
  name: Foscam 2
  ip: !secret foscam2_ip
  username: !secret foscam2_username
  password: !secret foscam2_password

#- platform: generic
#  still_image_url: !secret foscam1_stillimage
#  stream_source: !secret foscam1_stream
#  name: "Foscam 1"
#  verify_ssl: false

#- platform: generic
#  still_image_url: !secret foscam2_stillimage
#  stream_source: !secret foscam2_stream
#  name: "Foscam 2"
#  verify_ssl: false

#- platform: myfoscam
#  name: MyFoscam 1
#  ip: !secret foscam1_ip
#  username: !secret foscam1_username
#  password: !secret foscam1_password
#
#- platform: myfoscam
#  name: MyFoscam 2
#  ip: !secret foscam2_ip
#  username: !secret foscam2_username
#  password: !secret foscam2_password
