
- platform: foscam
  name: Foscam 1
  ip: !secret foscam1_ip
  username: !secret foscam1_username
  password: !secret foscam1_password

- platform: foscam
  name: Foscam 2
  ip: !secret foscam2_ip
  port: 88
  username: !secret foscam2_username
  password: !secret foscam2_password

- platform: foscam
  name: Foscam 3
  ip: !secret foscam3_ip
  rtsp_port: 88
  username: !secret foscam3_username
  password: !secret foscam3_password

#- platform: generic
#  stream_source: !secret foscam3_stream
#  still_image_url: !secret foscam3_stillimage
#  name: "Foscam 3"

#- platform: generic
#  stream_source: !secret mijia_camera_stream
#  still_image_url: /dev/shm/mijia_360_snapshot.jpg
#  name: "Mijia 360"

