
- platform: pushover
  name: pushover
  user_key: !secret pushover_user_key
  api_key: !secret pushover_api_key

#- name: email_anatoly
#  platform: smtp
#  server: smtp.gmail.com
#  port: 587
#  timeout: 15
#  sender: !secret google_username
#  username: !secret google_username
#  password: !secret google_passowrd
#  recipient: !secret google_recipient
#  encryption: starttls
#  sender_name: Home Assistant
