title: My Home
#background: center / cover no-repeat url("/local/images/background.jpg") fixed
# Include external resources
resources:
  - url: /local/custom_ui/slider-entity-row.js
    type: js
  - url: /local/custom_ui/card-tools.js?v=2
    type: js
  - url: /local/custom_ui/popup-card.js
    type: js
  - url: /local/custom_ui/bar-card.js?v0.0.5
    type: js

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed
# Exclude entities from "Unused entities" view
excluded_entities:
  - weblink.router
views:
  - !include lovelace/overview.yaml

  - !include lovelace/first_floor.yaml

  - !include lovelace/second_floor.yaml

  - !include lovelace/yard.yaml

  - !include lovelace/weather.yaml

  - !include lovelace/state.yaml

  - !include lovelace/settings.yaml

#  - !include lovelace/kiosk.yaml

