- platform: "mqtt"
  name: "ikea_lamp_13"
  state_topic: "zigbee2mqtt/ikea_lamp_13"
  availability_topic: "zigbee2mqtt/bridge/state"
  brightness: true
  color_temp: true
  schema: "json"
  command_topic: "zigbee2mqtt/ikea_lamp_13/set"
  brightness_scale: 255
