- platform: group
  name: Kitchen Lights 1
  entities:
  - light.ikea_lamp_4
  - light.ikea_lamp_5
  - light.ikea_lamp_6

- platform: group
  name: Kitchen Lights 2
  entities:
  - light.ikea_lamp_7
  - light.ikea_lamp_8
  - light.ikea_lamp_9

- platform: mqtt
  name: "Kitchen cupboard"
  state_topic: "zigbee2mqtt/ikea_plug_4"
  command_topic: "zigbee2mqtt/ikea_plug_4/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  optimistic: false
  brightness: false
  schema: "json"
  qos: 1
