- platform: group
  name: Kitchen Lights 1
  entities:
  - light.ikea_lamp_4
  - light.ikea_lamp_5
  - light.ikea_lamp_6

- platform: group
  name: Kitchen Lights 2
  entities:
  - light.ikea_lamp_7
  - light.ikea_lamp_8
  - light.ikea_lamp_9

- platform: switch
  name: "Kitchen cupboard"
  entity_id: switch.ikea_plug_4
