- platform: mqtt
  name: 'Pixie Channel 0'
  schema: json
  rgb: true
  brightness: true
  command_topic: "light_0fe4f0/channel0/set"
  state_topic: "light_0fe4f0/channel0"
  availability_topic: "light_0fe4f0/status"
  json_attributes_topic: "light_0fe4f0/attributes"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  qos: 0
  effect: true
  effect_list:
  - ColorLoop
  - Rainbow
  - DoubleRainbow
  - RainbowChase
  - RunningLights
  - TwoColors
  - ThreeColors
  - ColorPeaks
  - Stars
  - Comet
  - CometWithParticles
  - RandomComets
  - ColorFadings
  - SparklesOnColor
  - SparklesOnColorLoop
  - RandomMeteors
  - ColorFadings
  - SparklesOnColorLoop
  - RainbowWipesUp
  - RainbowWipesDown
  - RainbowWipesBackwards
  - ColorWipes
  - Chain
  - BrokenLamp
  - FastPixels
  - Stripes
  - Starburst
  - ColoredStarburst
  - RandomColoredStarburst
  - ColorPendulum
  - RainbowScan
  - DoubleRainbowScan
  - RandomColor
  - ChaseDown
  - ChaseUp
  - Chase2Down
  - Chase2Up
  - Meteors
  - Dots
  - RGBScanner
  - Stop


- platform: mqtt
  name: 'Pixie Channel 1'
  schema: json
  rgb: true
  brightness: true
  command_topic: "light_0fe4f0/channel1/set"
  state_topic: "light_0fe4f0/channel1"
  availability_topic: "light_0fe4f0/status"
  json_attributes_topic: "light_0fe4f0/attributes"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  qos: 0
  effect: true
  effect_list:
  - ColorLoop
  - Rainbow
  - DoubleRainbow
  - RainbowChase
  - RunningLights
  - TwoColors
  - ThreeColors
  - ColorPeaks
  - Stars
  - Comet
  - CometWithParticles
  - RandomComets
  - ColorFadings
  - SparklesOnColor
  - SparklesOnColorLoop
  - RandomMeteors
  - ColorFadings
  - SparklesOnColorLoop
  - RainbowWipesUp
  - RainbowWipesDown
  - RainbowWipesBackwards
  - ColorWipes
  - Chain
  - BrokenLamp
  - FastPixels
  - Stripes
  - Starburst
  - ColoredStarburst
  - RandomColoredStarburst
  - ColorPendulum
  - RainbowScan
  - DoubleRainbowScan
  - RandomColor
  - ChaseDown
  - ChaseUp
  - Chase2Down
  - Chase2Up
  - Meteors
  - Dots
  - RGBScanner
  - Stop
