- platform: mqtt
  name: 'Christams Pixie 1'
  schema: json
  rgb: true
  brightness: true
  command_topic: "light_0fe4e0/channel2/set"
  state_topic: "light_0fe4e0/channel2"
  availability_topic: "light_0fe4e0/status"
  json_attributes_topic: "light_0fe4e0/attributes"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  qos: 0
  effect: true
  effect_list:
  - ColorLoop
  - Rainbow
  - DoubleRainbow
  - RainbowChase
  - TwoColors
  - ThreeColors
  - ColorPeaks
  - Sparks
  - BigSparks
  - Comet
  - CometWithParticles
  - RandomComets
  - ColorFadings
  - SparklesOnColor
  - SparklesOnColorLoop
  - RainbowWipesUp
  - RainbowWipesDown
  - ColorWipes
  - Chain
  - BrokenLamp
  - FastPixels
  - BrightStripes
  - DarkStripes
  - Starburst
  - ColoredStarburst
  - RandomColoredStarburst
  - ColorPendulum
  - RainbowScan
  - DoubleRainbowScan
  - RandomColor
  - ChaseDown
  - ChaseUp
  - Chase2Down
  - Chase2Up
  - SporadicMeteors
  - Dots
  - RGBScanner
  - Twinkles
  - PixelQueue
  - PeriodicMeteorsUp
  - PeriodicMeteorsDown
  - Flicker
  - MultiplePixelQueues
  - Fireworks
  - Strobe
  - RunAndLightUp
  - Moths
  - Breathe
  - Pixie
  - EnergyHole
  - EnergySource
  - Neutrinos
  - MultipleColorPixelQueues


- platform: mqtt
  name: 'Christams Pixie 2'
  schema: json
  rgb: true
  brightness: true
  command_topic: "light_0fe4e0/channel3/set"
  state_topic: "light_0fe4e0/channel3"
  availability_topic: "light_0fe4e0/status"
  json_attributes_topic: "light_0fe4e0/attributes"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  qos: 0
  effect: true
  effect_list:
  - ColorLoop
  - Rainbow
  - DoubleRainbow
  - RainbowChase
  - TwoColors
  - ThreeColors
  - ColorPeaks
  - Sparks
  - BigSparks
  - Comet
  - CometWithParticles
  - RandomComets
  - ColorFadings
  - SparklesOnColor
  - SparklesOnColorLoop
  - RainbowWipesUp
  - RainbowWipesDown
  - ColorWipes
  - Chain
  - BrokenLamp
  - FastPixels
  - BrightStripes
  - DarkStripes
  - Starburst
  - ColoredStarburst
  - RandomColoredStarburst
  - ColorPendulum
  - RainbowScan
  - DoubleRainbowScan
  - RandomColor
  - ChaseDown
  - ChaseUp
  - Chase2Down
  - Chase2Up
  - SporadicMeteors
  - Dots
  - RGBScanner
  - Twinkles
  - PixelQueue
  - PeriodicMeteorsUp
  - PeriodicMeteorsDown
  - Flicker
  - MultiplePixelQueues
  - Fireworks
  - Strobe
  - RunAndLightUp
  - Moths
  - Breathe
  - Pixie
  - EnergyHole
  - EnergySource
  - Neutrinos
  - MultipleColorPixelQueues

