- platform: mqtt
  name: 'AQM CO₂'
  state_topic: "aqm_77c668"
  icon: mdi:molecule-co2
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppm"
  value_template: "{{ value_json.co2 }}"


- platform: mqtt
  name: 'AQM TVOC'
  state_topic: "aqm_77c668"
  icon: mdi:molecule
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppm"
  value_template: "{{ value_json.tvoc }}"


- platform: mqtt
  name: 'AQM Temperature'
  state_topic: "aqm_77c668"
  icon: mdi:temperature-celsius
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "℃"
  value_template: "{{ value_json.temperature }}"


- platform: mqtt
  name: 'AQM Humidity'
  state_topic: "aqm_77c668"
  icon: mdi:water-percent
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"


- platform: mqtt
  name: 'AQM PM0.3'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm0p3_ppd }}"


- platform: mqtt
  name: 'AQM PM0.5'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm0p5_ppd }}"


- platform: mqtt
  name: 'AQM PM1.0'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm1p0_ppd }}"


- platform: mqtt
  name: 'AQM PM2.5'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm2p5_ppd }}"


- platform: mqtt
  name: 'AQM PM5.0'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm5p0_ppd }}"


- platform: mqtt
  name: 'AQM PM10.0'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "ppd"
  value_template: "{{ value_json.pm10p0_ppd }}"


- platform: mqtt
  name: 'AQM PM1.0 Concentration'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "µg/m³"
  value_template: "{{ value_json.pm1p0_ae }}"

- platform: mqtt
  name: 'AQM PM2.5 Concentration'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "µg/m³"
  value_template: "{{ value_json.pm2p5_ae }}"

- platform: mqtt
  name: 'AQM PM10.0 Concentration'
  state_topic: "aqm_77c668"
  icon: mdi:air-filter
  availability_topic: "aqm_77c668/status"
  payload_available: "online"
  payload_not_available: "offline"
  unit_of_measurement: "µg/m³"
  value_template: "{{ value_json.pm10p0_ae }}"

