- platform: "mqtt"
  name: "keypad_1_battery"
  state_topic: "zigbee2mqtt/keypad_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "ikea_on_off_switch_1_battery"
  state_topic: "zigbee2mqtt/ikea_on_off_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "blinds_workroom_battery"
  state_topic: "zigbee2mqtt/blinds_workroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "blinds_guestroom_battery"
  state_topic: "zigbee2mqtt/blinds_guestroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "blinds_bedroom_battery_left"
  state_topic: "zigbee2mqtt/blinds_bedroom_left"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "blinds_bedroom_battery_right"
  state_topic: "zigbee2mqtt/blinds_bedroom_right"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "ikea_up_down_switch_1_battery"
  state_topic: "zigbee2mqtt/ikea_up_down_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "ikea_up_down_switch_2_battery"
  state_topic: "zigbee2mqtt/ikea_up_down_switch_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "ikea_up_down_switch_3_battery"
  state_topic: "zigbee2mqtt/ikea_up_down_switch_3"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

#-------------------------------------------------
#
# Ikea switches E1524/E1810
#
#-------------------------------------------------

- platform: "mqtt"
  name: "Ikea Switch 1 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 2 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 3 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_3"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 4 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_4"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 5 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_5"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 6 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_6"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

#-------------------------------------------------
#
# Xiaomi Weather sensor
#
#-------------------------------------------------
- platform: "mqtt"
  name: "Weather First Floor Battery"
  state_topic: "zigbee2mqtt/weather_first_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery }}"
  device_class: "battery"

- platform: "mqtt"
  name: "Weather Second Floor Battery"
  state_topic: "zigbee2mqtt/weather_second_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.battery }}"
  device_class: "battery"
