- platform: "mqtt"
  name: "keypad_1_battery"
  state_topic: "zigbee2mqtt/keypad_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
