- platform: "mqtt"
  name: "keypad_1_battery"
  state_topic: "zigbee2mqtt/keypad_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "ikea_on_off_switch_1_battery"
  state_topic: "zigbee2mqtt/ikea_on_off_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "blinds_workroom_battery"
  state_topic: "zigbee2mqtt/blinds_workroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
