- platform: mqtt
  name: 'Garden Light Temperature'
  state_topic: "light/garden1"
  icon: mdi:thermometer
  availability_topic: "light/garden/status"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "ËšC"
