- platform: "mqtt"
  name: "Ikea Switch 1 Battery"
  state_topic: "zigbee2mqtt/ikea_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "Ikea Switch 1 Signal"
  state_topic: "zigbee2mqtt/ikea_switch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:signal"
  unit_of_measurement: "lqi"
  value_template: "{{ value_json.linkquality }}"
