#-----------------------------------------------------------
#
# Illuminance sensor: xiaomi_illuminance_1
#
#-----------------------------------------------------------
- platform: "mqtt"
  name: "xiaomi_illuminance_1_battery"
  state_topic: "zigbee2mqtt/xiaomi_illuminance_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

- platform: "mqtt"
  name: "xiaomi_illuminance_1"
  state_topic: "zigbee2mqtt/xiaomi_illuminance_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: "xiaomi_illuminance_lux_1"
  state_topic: "zigbee2mqtt/xiaomi_illuminance_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance_lux }}"
