- platform: history_stats
  name: 'Bulb13 disconnects today'
  entity_id: light.bulb_13
  state: 'unavailable'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

