- platform: template
  sensors:
    nmap_router:
      entity_id: device_tracker.nmap_router
      friendly_name: 'Router'
      icon_template: mdi:router-wireless
      value_template: '{% if states.device_tracker.nmap_router.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_xiaomi_gateway:
      entity_id: device_tracker.nmap_xiaomi_gateway
      friendly_name: 'Xiaomi gateway'
      icon_template: mdi:access-point-network
      value_template: '{% if states.device_tracker.nmap_xiaomi_gateway.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_laptop_dell_xps15:
      entity_id: device_tracker.nmap_laptop_dell_xps15
      friendly_name: "Dell XPS 15"
      icon_template: mdi:laptop
      value_template: '{% if states.device_tracker.nmap_laptop_dell_xps15.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_google_home:
      entity_id: device_tracker.nmap_google_home
      friendly_name: 'Google home'
      icon_template: mdi:google-home
      value_template: '{% if states.device_tracker.nmap_google_home.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_iphone:
      entity_id: device_tracker.nmap_iphone
      friendly_name: "iPhone"
      icon_template: mdi:cellphone-iphone
      value_template: '{% if states.device_tracker.nmap_iphone.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_galaxy_s9:
      entity_id: device_tracker.nmap_galaxy_s9
      friendly_name: "Galaxy S9"
      icon_template: mdi:cellphone-android
      value_template: '{% if states.device_tracker.nmap_galaxy_s9.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'

- platform: template
  sensors:
    nmap_galaxy_tablet:
      entity_id: device_tracker.nmap_galaxy_tablet
      friendly_name: 'Galaxy S3 Tablet'
      icon_template: mdi:tablet-android
      value_template: '{% if states.device_tracker.nmap_galaxy_tablet.state == "home" %}
                         Connected
                       {% else %}
                         Disconnected
                       {% endif %}'
