- platform: folder
  folder: "/home/homeassistant/.homeassistant/media/Records"
  filter: "*.mp4"

- platform: folder
  folder: "/home/homeassistant/.homeassistant/media/Snapshots"
  filter: "*.jpg"

- platform: template
  sensors:
    number_of_records:
      friendly_name: "Number of records"
      value_template: "{{ state_attr('sensor.records', 'number_of_files') }}"
      icon_template: mdi:filmstrip
    number_of_snapshots:
      friendly_name: "Number of snapshots"
      value_template: "{{ state_attr('sensor.snapshots', 'number_of_files') }}"
      icon_template: mdi:image
