- platform: mqtt
  name: 'RSSI Bed light'
  state_topic: "light/bed"
  icon: mdi:wifi
  availability_topic: "light/bed/status"
  payload_available: "Online"
  payload_not_available: "Offline"
  value_template: "{{ value_json.rssi }}"
  unit_of_measurement: "dBm"

- platform: mqtt
  name: 'RSSI Keypad'
  state_topic: "alarm/keypad"
  icon: mdi:wifi
  availability_topic: "alarm/keypad/status"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.rssi }}"
  unit_of_measurement: "dBm"

- platform: mqtt
  name: 'RSSI Mood lamp'
  state_topic: "light/moodlamp"
  icon: mdi:wifi
  availability_topic: "light/moodlamp/status"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.rssi }}"
  unit_of_measurement: "dBm"

- platform: mqtt
  name: 'RSSI Garden Lights'
  state_topic: "light/garden1"
  icon: mdi:wifi
  availability_topic: "light/garden/status"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.rssi }}"
  unit_of_measurement: "dBm"

- platform: mqtt
  name: 'RSSI Informer'
  state_topic: "informer/state"
  icon: mdi:wifi
  availability_topic: "informer/status"
  payload_available: "online"
  payload_not_available: "offline"
  value_template: "{{ value_json.rssi }}"
  unit_of_measurement: "dBm"

