#########################################################
# First floor
#########################################################
- platform: "mqtt"
  name: "smoke_1_sensitivity"
  state_topic: "zigbee2mqtt/smoke_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.sensitivity }}"

- platform: "mqtt"
  name: "smoke_1_smoke_density"
  state_topic: "zigbee2mqtt/smoke_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.smoke_density }}"
  icon: "mdi:google-circles-communities"

#########################################################
# Second floor
#########################################################
- platform: "mqtt"
  name: "smoke_2_sensitivity"
  state_topic: "zigbee2mqtt/smoke_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.sensitivity }}"

- platform: "mqtt"
  name: "smoke_2_smoke_density"
  state_topic: "zigbee2mqtt/smoke_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "-"
  value_template: "{{ value_json.smoke_density }}"
  icon: "mdi:google-circles-communities"
