- platform: template
  sensors:
    sunset_time:
      entity_id: sun.sun
      value_template: "{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}"
      friendly_name: Sunset
      icon_template: mdi:weather-sunset-down
    sunrise_time:
      entity_id: sun.sun
      value_template: "{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%H:%M') %} {{ timestamp.lstrip('0') }}"
      friendly_name: Sunrise
      icon_template: mdi:weather-sunset-up
    solar_angle:
      entity_id: sun.sun
      value_template: "{{ states.sun.sun.attributes.elevation }}"
      friendly_name: Solar Angle
      unit_of_measurement: '°'
      icon_template: mdi:weather-sunny

