#-----------------------------------------------------
#
#   TuYa Weather sensor 1
#
#-----------------------------------------------------
- platform: "mqtt"
  name: "tuya_temperature_1"
  state_topic: "zigbee2mqtt/tuya_weather_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature }}"

- platform: "mqtt"
  name: "tuya_humidity_1"
  state_topic: "zigbee2mqtt/tuya_weather_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity }}"

- platform: "mqtt"
  name: "tuya_weather_1_battery"
  state_topic: "zigbee2mqtt/tuya_weather_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"
