- platform: vasttrafik
  key: !secret vasttrafik_key
  secret: !secret vasttrafik_secret
  departures:
  - name: "Västtrafik Linje 176 mot Lindholmen"
    from: !secret vasttrafik_my_stop1
    heading: "Hjalmar Brantingsplatsen"
    lines:
      - 176
  - name: "Västtrafik Linje 176 mot Rannebergen"
    from: "Hjalmar Brantingsplatsen"
    heading: !secret vasttrafik_my_stop1
    lines:
      - 176
  - name: "Västtrafik Linje 177 mot Lövgärdet"
    from: "Hjalmar Brantingsplatsen"
    heading: !secret vasttrafik_my_stop2
    lines:
      - 177
  - name: "Västtrafik Linje 177 mot Lindholmen"
    from: !secret vasttrafik_my_stop2
    heading: "Hjalmar Brantingsplatsen"
    lines:
      - 177


#- platform: template
#  sensors:
#    vasttrafik_line_75:
#      icon_template: mdi:bus
#      friendly_name: 'Line 75'
#      value_template: '{% if states.sensor.vasttrafik_transport.attributes.line|int == 75 %}
#                         {{ states.sensor.vasttrafik_transport.state }}
#                      {% else %}
#                         --:--
#                      {% endif %}'
#
#
#- platform: template
#  sensors:
#    vasttrafik_line_176:
#      icon_template: mdi:bus
#      friendly_name: 'Line 176'
#      value_template: '{% if states.sensor.vasttrafik_transport.attributes.line|int == 176 %}
#                         {{ states.sensor.vasttrafik_transport.state }}
#                      {% else %}
#                         --:--
#                      {% endif %}'
