- platform: "mqtt"
  name: "Temperature First Floor"
  state_topic: "zigbee2mqtt/weather_first_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temperature }}"
  device_class: "temperature"

- platform: "mqtt"
  name: "Humidity First Floor"
  state_topic: "zigbee2mqtt/weather_first_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
  device_class: "humidity"

- platform: "mqtt"
  name: "Pressure First Floor"
  state_topic: "zigbee2mqtt/weather_first_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: "{{ value_json.pressure }}"
  device_class: "pressure"

#-------------------

- platform: "mqtt"
  name: "Temperature Second Floor"
  state_topic: "zigbee2mqtt/weather_second_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temperature }}"
  device_class: "temperature"

- platform: "mqtt"
  name: "Humidity Second Floor"
  state_topic: "zigbee2mqtt/weather_second_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
  device_class: "humidity"

- platform: "mqtt"
  name: "Pressure Second Floor"
  state_topic: "zigbee2mqtt/weather_second_floor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: "{{ value_json.pressure }}"
  device_class: "pressure"

#-------------------

- platform: "mqtt"
  name: "Temperature Storehouse"
  state_topic: "zigbee2mqtt/weather_storehouse"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temperature }}"
  device_class: "temperature"

- platform: "mqtt"
  name: "Humidity Storehouse"
  state_topic: "zigbee2mqtt/weather_storehouse"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
  device_class: "humidity"

- platform: "mqtt"
  name: "Pressure Storehouse"
  state_topic: "zigbee2mqtt/weather_storehouse"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: "{{ value_json.pressure }}"
  device_class: "pressure"

#-------------------

- platform: "mqtt"
  name: "Temperature Outdoor"
  state_topic: "zigbee2mqtt/weather_outdoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "째C"
  value_template: "{{ value_json.temperature }}"
  device_class: "temperature"

- platform: "mqtt"
  name: "Humidity Outdoor"
  state_topic: "zigbee2mqtt/weather_outdoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  value_template: "{{ value_json.humidity }}"
  device_class: "humidity"

- platform: "mqtt"
  name: "Pressure Outdoor"
  state_topic: "zigbee2mqtt/weather_outdoor"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "hPa"
  value_template: "{{ value_json.pressure }}"
  device_class: "pressure"

