#-------------------------------------------------
#
# Motion / Illuminance sensor in the workroom
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_workroom'
  state_topic: "zigbee2mqtt/motion_workroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_workroom_battery'
  state_topic: "zigbee2mqtt/motion_workroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor upstairs
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_upstairs'
  state_topic: "zigbee2mqtt/motion_upstairs"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_upstairs_battery'
  state_topic: "zigbee2mqtt/motion_upstairs"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor in the guestroom
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_guestroom'
  state_topic: "zigbee2mqtt/motion_guestroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_guestroom_battery'
  state_topic: "zigbee2mqtt/motion_guestroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor in the bedroom
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_bedroom'
  state_topic: "zigbee2mqtt/motion_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_bedroom_battery'
  state_topic: "zigbee2mqtt/motion_bedroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor in the living room
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_livingroom'
  state_topic: "zigbee2mqtt/motion_livingroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_livingroom_battery'
  state_topic: "zigbee2mqtt/motion_livingroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor in the entrance
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_entrance'
  state_topic: "zigbee2mqtt/motion_entrance"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_entrance_battery'
  state_topic: "zigbee2mqtt/motion_entrance"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"


#-------------------------------------------------
#
# Motion / Illuminance sensor in the kitchen
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_kitchen'
  state_topic: "zigbee2mqtt/motion_kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_kitchen_battery'
  state_topic: "zigbee2mqtt/motion_kitchen"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

#-------------------------------------------------
#
# Motion / Illuminance sensor in the backyard
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_backyard'
  state_topic: "zigbee2mqtt/motion_backyard"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_backyard_battery'
  state_topic: "zigbee2mqtt/motion_backyard"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

#-------------------------------------------------
#
# Motion / Illuminance sensor in the frontyard
#
#-------------------------------------------------
- platform: "mqtt"
  name: 'lightlevel_frontyard'
  state_topic: "zigbee2mqtt/motion_frontyard"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "lx"
  device_class: "illuminance"
  value_template: "{{ value_json.illuminance }}"

- platform: "mqtt"
  name: 'motion_frontyard_battery'
  state_topic: "zigbee2mqtt/motion_frontyard"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "%"
  device_class: "battery"
  value_template: "{{ value_json.battery }}"

