- platform: "mqtt"
  name: "xiaomi_relay_1_power"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "W"
  value_template: "{{ value_json.power }}"
  icon: "mdi:flash"

- platform: "mqtt"
  name: "xiaomi_relay_1_energy"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "kWh"
  value_template: "{{ value_json.energy }}"
  icon: "mdi:power-plug"

- platform: "mqtt"
  name: "xiaomi_relay_1_temperature"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.temperature }}"
  device_class: "temperature"

- platform: "mqtt"
  name: "xiaomi_relay_1_voltage"
  state_topic: "zigbee2mqtt/xiaomi_relay_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  unit_of_measurement: "V"
  value_template: "{{ value_json.voltage }}"
  icon: "mdi:alpha-v"
