- platform: "mqtt"
  name: "Xiaomi Powerswitch 1 Temperature"
  state_topic: "zigbee2mqtt/xiaomi_powerswitch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.temperature }}"
  unit_of_measurement: "°C"
  device_class: "temperature"

- platform: "mqtt"
  name: "Xiaomi Powerswitch 1 Power"
  state_topic: "zigbee2mqtt/xiaomi_powerswitch_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.power }}"
  unit_of_measurement: "W"
  device_class: "power"
