- platform: ping
  name: Foscam1
  host: !secret foscam1_ip
  count: 2
  scan_interval: 30

- platform: ping
  name: Foscam2
  host: !secret foscam2_ip
  count: 2
  scan_interval: 30

- platform: ping
  name: Foscam3
  host: !secret foscam3_ip
  count: 2
  scan_interval: 30
