- platform: mqtt
  name: 'Motion Upstairs'
  state_topic: 'motion/upstairs'
  payload_on: 'on'
  payload_off: 'off'
  availability_topic: "light/stairs/status"
  device_class: 'motion'

- platform: mqtt
  name: 'Motion Downstairs'
  state_topic: 'motion/downstairs'
  payload_on: 'on'
  payload_off: 'off'
  availability_topic: "light/stairs/status"
  device_class: 'motion'
