- platform: mqtt
  name: 'Motion Upstairs'
  state_topic: 'motion/upstairs'
  payload_on: 1
  payload_off: 0
  availability_topic: "light/stairs/status"
  device_class: 'motion'

- platform: mqtt
  name: 'Motion Downstairs'
  state_topic: 'motion/downstairs'
  payload_on: 1
  payload_off: 0
  availability_topic: "light/stairs/status"
  device_class: 'motion'
