- platform: "mqtt"
  name: "water_leak_1"
  state_topic: "zigbee2mqtt/water_leak_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.water_leak }}"
  payload_on: true
  payload_off: false
  device_class: "moisture"

- platform: "mqtt"
  name: "water_leak_1_battery_low"
  state_topic: "zigbee2mqtt/water_leak_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.battery_low }}"
  payload_on: true
  payload_off: false
  device_class: "battery"

- platform: "mqtt"
  name: "water_leak_1_tamper"
  state_topic: "zigbee2mqtt/water_leak_1"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.tamper }}"
  payload_on: true
  payload_off: false

#-----------------------

- platform: "mqtt"
  name: "water_leak_2"
  state_topic: "zigbee2mqtt/water_leak_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.water_leak }}"
  payload_on: true
  payload_off: false
  device_class: "moisture"

- platform: "mqtt"
  name: "water_leak_2_battery_low"
  state_topic: "zigbee2mqtt/water_leak_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.battery_low }}"
  payload_on: true
  payload_off: false
  device_class: "battery"

- platform: "mqtt"
  name: "water_leak_2_tamper"
  state_topic: "zigbee2mqtt/water_leak_2"
  availability_topic: "zigbee2mqtt/bridge/state"
  value_template: "{{ value_json.tamper }}"
  payload_on: true
  payload_off: false

