- platform: "mqtt"
  name: "blinds_bedroom_left"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/blinds_bedroom_left/set"
  position_topic: "zigbee2mqtt/blinds_bedroom_left"
  set_position_topic: "zigbee2mqtt/blinds_bedroom_left/set"
  set_position_template: "{ \"position\": {{ position }} }"
  position_template: "{{ value_json.position }}"

- platform: "mqtt"
  name: "blinds_bedroom_right"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/blinds_bedroom_right/set"
  position_topic: "zigbee2mqtt/blinds_bedroom_right"
  set_position_topic: "zigbee2mqtt/blinds_bedroom_right/set"
  set_position_template: "{ \"position\": {{ position }} }"
  position_template: "{{ value_json.position }}"
