- platform: "mqtt"
  name: "blinds_workroom"
  availability_topic: "zigbee2mqtt/bridge/state"
  command_topic: "zigbee2mqtt/blinds_workroom/set"
  position_topic: "zigbee2mqtt/blinds_workroom"
  set_position_topic: "zigbee2mqtt/blinds_workroom/set"
  set_position_template: "{ \"position\": {{ position }} }"
  value_template: "{{ value_json.position }}"
