- alias: '[Alarm] Trigger alarm while armed away'
  initial_state: true
  trigger:
    - platform: state 
      entity_id: binary_sensor.openclose_livingroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_entrance
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_kitchen
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_storehouse
      to: 'on'

    - platform: state 
      entity_id: binary_sensor.presence_livingroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_entrance
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_kitchen
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_upstairs
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_workroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_bedroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_room
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'armed_away'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house



- alias: '[Alarm] Trigger alarm if any door is open while armed home'
  initial_state: true
  trigger:
    - platform: state 
      entity_id: binary_sensor.openclose_livingroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_entrance
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_kitchen
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_storehouse
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'armed_home'
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house


- alias: '[Alarm] Trigger alarm if any door is open while armed night'
  initial_state: true
  trigger:
  - platform: state 
    entity_id: binary_sensor.openclose_livingroom
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_entrance
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_kitchen
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_storehouse
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_night'
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house


