- alias: 'Trigger alarm while armed away'
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d00022bd3cb #Living room door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d000238694e #Entrance door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d000232d8e8 #Kitchen door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_storehouse
      to: 'on'

    - platform: state 
      entity_id: binary_sensor.presence_livingroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.motion_sensor_158d000236a817 #Entrance
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_kitchen
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_upstairs #Second floor
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_workroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_bedroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_room
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house



- alias: 'Trigger alarm while armed home'
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d00022bd3cb #Living room door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d000238694e #Entrance door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.door_window_sensor_158d000232d8e8 #Kitchen door
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.openclose_storehouse
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_home
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.house

