- alias: '[Alarm] Disarm Armed_Home if motion on the first floor'
  initial_state: true
  trigger:
    - platform: state 
      entity_id: binary_sensor.presence_livingroom
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_entrance
      to: 'on'
    - platform: state 
      entity_id: binary_sensor.presence_kitchen
      to: 'on'
#    - platform: state 
#      entity_id: binary_sensor.presence_upstairs #Second floor
#      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.house
      state: armed_home
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

