- alias: '[Alarm] Arm night automatically'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.all_in_bed
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_night
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

- alias: '[Alarm] Disarm night automatically'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.all_in_bed
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_night'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

- alias: '[Alarm] Pending from armed_night'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: 'armed_night'
    to: 'pending'
  action:
  - service: automation.turn_on
    entity_id: automation.alarm_pending_sound
  - service: light.turn_on
    data:
      entity_id: light.kitchen_lights_1
      brightness_pct: 100
  - service: light.turn_on
    data:
      entity_id: light.kitchen_lights_2
      brightness_pct: 100
  - service: light.turn_on
    data:
      entity_id: light.ikea_lamp_1
      brightness_pct: 100
  - service: light.turn_on
    data:
      entity_id: light.ikea_lamp_13
      brightness_pct: 100


# =========> Arming/Pending
- alias: '[Alarm] Pending sound while pending from disarmed state'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'arming'
  action:
  - service: automation.turn_on
    entity_id: automation.alarm_pending_sound


- alias: '[Alarm] Pending sound while pending from armed away'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'
  action:
  - service: automation.turn_on
    entity_id: automation.alarm_pending_sound

# =========> Armed Away
- alias: '[Alarm] Armed Away has been armed'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_away'
  action:
  - service: notify.pushover
    data:
      title: "Alarm is armed"
      message: "The alarm has been armed away."
  - service: automation.turn_off
    entity_id: automation.alarm_pending_sound
  - service: light.turn_off
    data:
      entity_id: group.indoor_lights


# =========> Armed Home
- alias: '[Alarm] Armed Home has been armed'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_home'
  action:
  - service: notify.pushover
    data:
      title: "Alarm is armed"
      message: "The alarm has been armed home."
  - service: automation.turn_off
    entity_id: automation.alarm_pending_sound


# ==============> Disarmed
- alias: '[Alarm] Disarmed'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  action:
  - service: script.turn_on
    data:
      entity_id: script.alarm_off


# =============> Triggered
- alias: '[Alarm] Triggered'
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
  action:
  - service: script.turn_on
    data:
      entity_id: script.alarm_on

