- alias: '[Alarm] Alarm Sound RPi Speaker'
  hide_entity: true
  initial_state: False
  trigger:
  - platform: time_pattern
    seconds: "/1"
  action:
  - service: shell_command.alarm_sound_rpi_speaker


