# =========> Arming/Pending
- alias: '[Alarm] Away Mode Arming'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'
  action:
  - service: light.turn_on
    entity_id: light.gateway_light_7811dcb7f720
    data:
      brightness: 255
      rgb_color: [0, 0, 255]
  - service: automation.turn_on
    entity_id: automation.alarm_pending_sound


# =========> Armed Away
- alias: '[Alarm] Armed Away'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_away'
  action:
  - service: notify.pushover
    data:
      message: "The Away alarm has been armed."
  - service: automation.turn_off
    entity_id: automation.alarm_pending_sound
  - service: light.turn_off
    data:
      entity_id: group.all_lights


# =========> Armed Home
- alias: '[Alarm] Armed Home'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'armed_home'
  action:
  - service: notify.pushover
    data:
      message: "The Home alarm has been armed."
  - service: automation.turn_off
    entity_id: automation.alarm_pending_sound


# ==============> Disarmed
- alias: '[Alarm] Disarmed'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  action:
  - service: script.turn_on
    data:
      entity_id: script.alarm_off


# =============> Triggered
- alias: '[Alarm] Triggered'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'triggered'
  action:
  - service: script.turn_on
    data:
      entity_id: script.alarm_on
