- alias: '[Keypad] Arm alarm in armed_away'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code


- alias: '[Keypad] Disarm alarm from armed_away'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code


- alias: '[Keypad] Disarm alarm while pending'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'pending'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

- alias: '[Keypad] Disarm alarm while triggered'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'triggered'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

