- alias: 'Arm alarm from MQTT Keypad'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code


- alias: 'Disarm alarm from MQTT Keypad'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code


- alias: 'Disarm alarm from MQTT Keypad while pending'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'pending'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

- alias: 'Disarm alarm from MQTT Keypad while triggered'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: !secret alarm_code
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'triggered'
  action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.house
    data:
      code: !secret alarm_code

