
- alias: '[All In Bed Alarm] Trigger if any door is open'
  initial_state: true
  hide_entity: true
  trigger:
  - platform: state 
    entity_id: binary_sensor.openclose_livingroom
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_entrance
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_kitchen
    to: 'on'
  - platform: state 
    entity_id: binary_sensor.openclose_storehouse #Storagehouse door
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: group.all_lights
  - service: notify.pushover
    data:
      title: "ALARM"
      message: "A door is open while everyone is sleeping"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "ALARM"
      message: "A door is open while everyone is sleeping"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "ALARM"
      message: "A door is open while everyone is sleeping"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "ALARM"
      message: "A door is open while everyone is sleeping"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "ALARM"
      message: "A door is open while everyone is sleeping"

