- alias: '[All in bed] Run script every 10 minutes if off'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  action:
  - service: python_script.all_in_bed


- alias: '[All in bed] Run script if motion and sensor is on'
  hide_entity: true
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000236a817 #Entrance
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000200ce6a #Kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00023e8333 #Living room
      to: 'on'
    - platform: state
      entity_id: binary_sensor.presence_upstairs
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000236a581 #Work room
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000236be32 #Room
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.all_in_bed
      state: 'on'
  action:
    - service: python_script.all_in_bed


- alias: "[All in bed] Run script on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: python_script.all_in_bed
