- alias: '[All In Bed] Run script every 10 minutes if off'
  initial_state: true
  trigger:
  - platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  action:
  - service: python_script.all_in_bed


- alias: '[All In Bed] Run script if motion and sensor is on'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_entrance
      to: 'on'
    - platform: state
      entity_id: binary_sensor.presence_kitchen
      to: 'on'
    - platform: state
      entity_id: binary_sensor.presence_livingroom
      to: 'on'
    - platform: state
      entity_id: binary_sensor.presence_upstairs
      to: 'on'
    - platform: state
      entity_id: binary_sensor.presence_workroom
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.all_in_bed
      state: 'on'
  action:
    - service: python_script.all_in_bed


- alias: "[All In Bed] Run script on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: python_script.all_in_bed

