- alias: '[System] Any battery is low'
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.smoke_1_battery
    - sensor.smoke_2_battery
    - sensor.xiaomi_button_1_battery
    - sensor.xiaomi_button_2_battery
    - sensor.openclose_kitchen_battery
    - sensor.openclose_livingroom_battery
    - sensor.openclose_entrance_battery
    - sensor.openclose_storehouse_battery
    - sensor.ikea_switch_1_battery
    - sensor.ikea_switch_2_battery
    - sensor.ikea_switch_3_battery
    - sensor.ikea_switch_4_battery
    - sensor.ikea_switch_5_battery
    - sensor.ikea_switch_6_battery
    - sensor.xiaomi_wallswitch_1_battery_level
    - sensor.weather_outdoor_battery
    - sensor.weather_first_floor_battery
    - sensor.weather_second_floor_battery
    - sensor.weather_storehouse_battery
    - sensor.water_leak_1_battery
    - sensor.water_leak_2_battery
    - sensor.ikea_on_off_switch_1_battery
    - sensor.ikea_on_off_switch_2_battery_level
    - sensor.ikea_up_down_switch_1_battery
    - sensor.ikea_up_down_switch_2_battery
    - sensor.ikea_up_down_switch_3_battery
    - sensor.blinds_guesroom_battery
    - sensor.blinds_workroom_battery
    - sensor.blinds_bedroom_right_battery
    - sensor.blinds_bedroom_left_battery
    - sensor.xiaomi_oppleswitch_1_battery
    - sensor.motion_workroom_battery
    - sensor.motion_upstairs_battery
    - sensor.motion_guestroom_battery
    - sensor.motion_bedroom_battery
    - sensor.motion_kitchen_battery
    - sensor.motion_entrance_battery
    - sensor.motion_livingroom_battery
    - sensor.motion_backyard_battery
    - sensor.keypad_1_battery
    - sensor.tuya_weather_1_battery
    below: 15
  mode: queued
  action:
  - choose:

    #----------------------
    # Left cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_left_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the left cover in the bedroom is {{ states('sensor.blinds_bedroom_left_battery') }} %."

    # Right cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_right_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the right cover in the bedroom is {{ states('sensor.blinds_bedroom_right_battery') }} %."

    # Cover in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_guesroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the guestroom is {{ states('sensor.blinds_guesroom_battery') }} %."

    # Cover in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_workroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the workroom is {{ states('sensor.blinds_workroom_battery') }} %."

    #----------------------
    # Ikea Switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 1 is {{ states('sensor.ikea_switch_1_battery') }} %."

    # Ikea Switch 4
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_4_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 4 is {{ states('sensor.ikea_switch_4_battery') }} %."

    # Ikea Switch 3
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_3_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 3 is {{ states('sensor.ikea_switch_3_battery') }} %."

    # Ikea Switch 6
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_6_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 6 is {{ states('sensor.ikea_switch_6_battery') }} %."

    # Ikea Switch 2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 2 is {{ states('sensor.ikea_switch_2_battery') }} %."

    # Ikea Switch 5
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_5_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 5 is {{ states('sensor.ikea_switch_5_battery') }} %."

    #----------------------
    # Motion sensor in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_workroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the workroom is {{ states('sensor.motion_workroom_battery') }} %."

    # Motion sensor upstairs
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_upstairs_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor upstairs is {{ states('sensor.motion_upstairs_battery') }} %."

    # Motion sensor in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_guestroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the guestroom is {{ states('sensor.motion_guestroom_battery') }} %."

    # Motion sensor in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_bedroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the bedroom is {{ states('sensor.motion_bedroom_battery') }} %."

    # Motion sensor in the kitchen
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_kitchen_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the kitchen is {{ states('sensor.motion_kitchen_battery') }} %."

    # Motion sensor in the living room
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_livingroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the living room is {{ states('sensor.motion_livingroom_battery') }} %."

    # Motion sensor in the entrance
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_entrance_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor at the entrance is {{ states('sensor.motion_entrance_battery') }} %."

    # Motion sensor in the backyard
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_backyard_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the backyard is {{ states('sensor.motion_backyard_battery') }} %."

    #----------------------
    # Keypad 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.keypad_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the keypad 1 is {{ states('sensor.keypad_1_battery') }} %."

    #----------------------
    # IKEA on/off switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_on_off_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA on/off switch 1 is {{ states('sensor.ikea_on_off_switch_1_battery') }} %."
    
    #----------------------
    # IKEA up/down switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 1 is {{ states('sensor.ikea_up_down_switch_1_battery') }} %."
    
    # IKEA up/down switch 2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 2 is {{ states('sensor.ikea_up_down_switch_2_battery') }} %."

    # IKEA up/down switch 3
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_3_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 3 is {{ states('sensor.ikea_up_down_switch_3_battery') }} %."

    #----------------------
    # TuYa Weather sensor 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.tuya_weather_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the TuYa weather sensor 1 is {{ states('sensor.tuya_weather_1_battery') }} %."

    # Xiaomi Weather First Floor sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_first_floor_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the weather sensor on the first floor is {{ states('sensor.weather_first_floor_battery') }} %."

    # Xiaomi Weather Second Floor sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_second_floor_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the weather sensor on the second floor is {{ states('sensor.weather_second_floor_battery') }} %."

    # Xiaomi Weather Storehouse sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_storehouse_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the weather sensor in the storehouse is {{ states('sensor.weather_storehouse_battery') }} %."

    # Outdoor weather sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_outdoor_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the outdoor weather sensor is {{ states('sensor.weather_outdoor_battery') }} %."

    #----------------------
    # xiaomi_button_1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.xiaomi_button_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the xiaomi button 1 (doorbell) is {{ states('sensor.xiaomi_button_1_battery') }} %."

    # xiaomi_button_2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.xiaomi_button_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the xiaomi button 2 (Bedroom) is {{ states('sensor.xiaomi_button_2_battery') }} %."

    #----------------------
    # openclose_entrance
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.openclose_entrance_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the entrance door sensor is {{ states('sensor.openclose_entrance_battery') }} %."

    # openclose_kitchen
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.openclose_kitchen_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the kitchen door sensor is {{ states('sensor.openclose_kitchen_battery') }} %."

    # openclose_livingroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.openclose_livingroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the kitchen door sensor is {{ states('sensor.openclose_livingroom_battery') }} %."

    # openclose_storehouse
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.openclose_storehouse_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the store house door sensor is {{ states('sensor.openclose_storehouse_battery') }} %."

    #----------------------
    # Smoke detector 1 floor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.smoke_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the smoke sensor on the 1st floor is {{ states('sensor.smoke_1_battery') }} %."

    # Smoke detector 2 floor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.smoke_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the smoke sensor on the 2nd floor is {{ states('sensor.smoke_2_battery') }} %."

    #---------------------------
    # xiaomi_oppleswitch_1_battery
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.xiaomi_oppleswitch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Opple switch 1 is {{ states('sensor.xiaomi_oppleswitch_1_battery') }} %."

    #----------------------
    # Water detector 1 
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.water_leak_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the water leak sensor 1 is {{ states('sensor.water_leak_1_battery') }} %."

    # Water detector 2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.water_leak_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the water leak sensor 2 is {{ states('sensor.water_leak_2_battery') }} %."

    default:
    - service: notify.pushover
      data_template:
        title: "Low battery"
        message: "The battery of {{ trigger.to_state.entity_id }} is {{ trigger.to_state.state }} %."



- alias: '[System] Battery of Smoke detectors'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.smoke_1_battery_low
    - binary_sensor.smoke_2_battery_low
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'binary_sensor.smoke_1_battery_low' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "⚠ Low battery"
          message: "The battery of the smoke sensor on the first floor is low: {{ states('sensor.smoke_1_battery') }} %."

    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'binary_sensor.smoke_2_battery_low' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "⚠ Low battery"
          message: "The battery of the smoke sensor on the second floor is low: {{ states('sensor.smoke_2_battery') }} %."


- alias: '[System] Battery of Water detectors'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_1_battery_low
    - binary_sensor.water_leak_2_battery_low
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'binary_sensor.water_leak_1_battery_low' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "⚠ Low battery"
          message: "The battery of the water leak sensor 1 is low: {{ states('sensor.water_leak_1_battery') }} %."

    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'binary_sensor.water_leak_2_battery_low' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "⚠ Low battery"
          message: "The battery of the water leak sensor 2 is low: {{ states('sensor.water_leak_2_battery') }} %."

