- alias: '[System] Any battery is low'
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_switch_workroom_battery_level
    - sensor.xiaomi_switch_bedroom_battery_level
    - sensor.motion_sensor_kitchen_battery_level
    - sensor.motion_sensor_backyard_battery_level
    - sensor.motion_sensor_entrance_battery_level
    - sensor.kitchen_battery_level
    - sensor.motion_sensor_livingroom_battery_level
    - sensor.living_room_battery_level
    - sensor.entrance_battery_level
    - sensor.storehouse_battery_level
    - sensor.ikea_switch_1_battery
    - sensor.ikea_switch_2_battery_level
    - sensor.ikea_switch_3_battery_level
    - sensor.ikea_switch_4_battery_level
    - sensor.ikea_switch_5_battery_level
    - sensor.xiaomi_wallswitch_1_battery_level
    - sensor.weather_storehouse_battery_level
    - sensor.weather_second_floor_battery_level
    - sensor.weather_first_floor_battery_level
    - sensor.weather_outdoor_battery_level
    - sensor.water_first_floor_battery_level
    - sensor.water_second_floor_battery_level
    - sensor.ikea_on_off_switch_1_battery_level
    - sensor.ikea_on_off_switch_2_battery_level
    - sensor.ikea_up_down_switch_1_battery_level
    - sensor.ikea_up_down_switch_2_battery_level
    - sensor.ikea_up_down_switch_3_battery_level
    - sensor.smoke_first_floor_battery_level
    - sensor.smoke_second_floor_battery_level
    - sensor.blinds_guesroom_battery_level
    - sensor.blinds_workroom_battery_level
    - sensor.blinds_bedroom_right_battery_level
    - sensor.blinds_bedroom_left_battery_level
    - sensor.opple_switch_1_battery_level
    - sensor.motion_workroom_battery
    - sensor.motion_upstairs_battery
    - sensor.motion_guestroom_battery
    - sensor.motion_bedroom_battery
    - sensor.keypad_1_battery
    below: 20
  mode: queued
  action:
  - choose:

    # Outdoor weather sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_outdoor_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the outdoor weather sensor is {{ states('sensor.weather_outdoor_battery_level') }} %."

    # Left cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_left_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the left cover in the bedroom is {{ states('sensor.blinds_bedroom_left_battery_level') }} %."

    # Right cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_right_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the right cover in the bedroom is {{ states('sensor.blinds_bedroom_right_battery_level') }} %."

    # Cover in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_guesroom_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the guestroom is {{ states('sensor.blinds_guesroom_battery_level') }} %."

    # Cover in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_workroom_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the workroom is {{ states('sensor.blinds_workroom_battery_level') }} %."

    # Ikea Switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 1 is {{ states('sensor.ikea_switch_1_battery') }} %."

    # Motion sensor in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_workroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the workroom is {{ states('sensor.motion_workroom_battery') }} %."

    # Motion sensor upstairs
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_upstairs_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor upstairs is {{ states('sensor.motion_upstairs_battery') }} %."

    # Motion sensor in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_guestroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the guestroom is {{ states('sensor.motion_guestroom_battery') }} %."

    # Motion sensor in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_bedroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the bedroom is {{ states('sensor.motion_bedroom_battery') }} %."

    # Keypad 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.keypad_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the keypad 1 is {{ states('sensor.keypad_1_battery') }} %."

    default:
    - service: notify.pushover
      data_template:
        title: "Low battery"
        message: "The battery of {{ trigger.to_state.entity_id }} is {{ trigger.to_state.state }} %."




