- alias: '[System] Any battery is low'
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_switch_workroom_battery_level
    - sensor.xiaomi_switch_bedroom_battery_level
    - sensor.motion_sensor_backyard_battery_level
    - sensor.kitchen_battery_level
    - sensor.living_room_battery_level
    - sensor.entrance_battery_level
    - sensor.storehouse_battery_level
    - sensor.ikea_switch_1_battery
    - sensor.ikea_switch_2_battery
    - sensor.ikea_switch_3_battery
    - sensor.ikea_switch_4_battery_level
    - sensor.ikea_switch_5_battery
    - sensor.ikea_switch_6_battery
    - sensor.xiaomi_wallswitch_1_battery_level
    - sensor.weather_storehouse_battery_level
    - sensor.weather_second_floor_battery_level
    - sensor.weather_first_floor_battery_level
    - sensor.weather_outdoor_battery_level
    - sensor.water_first_floor_battery_level
    - sensor.water_second_floor_battery_level
    - sensor.ikea_on_off_switch_1_battery
    - sensor.ikea_on_off_switch_2_battery_level
    - sensor.ikea_up_down_switch_1_battery
    - sensor.ikea_up_down_switch_2_battery
    - sensor.ikea_up_down_switch_3_battery
    - sensor.smoke_first_floor_battery_level
    - sensor.smoke_second_floor_battery_level
    - sensor.blinds_guesroom_battery
    - sensor.blinds_workroom_battery
    - sensor.blinds_bedroom_right_battery
    - sensor.blinds_bedroom_left_battery
    - sensor.opple_switch_1_battery_level
    - sensor.motion_workroom_battery
    - sensor.motion_upstairs_battery
    - sensor.motion_guestroom_battery
    - sensor.motion_bedroom_battery
    - sensor.motion_kitchen_battery
    - sensor.motion_entrance_battery
    - sensor.motion_livingroom_battery
    - sensor.keypad_1_battery
    - sensor.tuya_weather_1_battery
    below: 20
  mode: queued
  action:
  - choose:

    # Outdoor weather sensor
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.weather_outdoor_battery_level' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the outdoor weather sensor is {{ states('sensor.weather_outdoor_battery_level') }} %."

    # Left cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_left_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the left cover in the bedroom is {{ states('sensor.blinds_bedroom_left_battery') }} %."

    # Right cover in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_bedroom_right_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the right cover in the bedroom is {{ states('sensor.blinds_bedroom_right_battery') }} %."

    # Cover in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_guesroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the guestroom is {{ states('sensor.blinds_guesroom_battery') }} %."

    # Cover in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.blinds_workroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the cover in the workroom is {{ states('sensor.blinds_workroom_battery') }} %."

    # Ikea Switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 1 is {{ states('sensor.ikea_switch_1_battery') }} %."

    # Ikea Switch 4
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_4_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 4 is {{ states('sensor.ikea_switch_4_battery') }} %."

    # Ikea Switch 3
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_3_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 3 is {{ states('sensor.ikea_switch_3_battery') }} %."

    # Ikea Switch 6
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_6_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 6 is {{ states('sensor.ikea_switch_6_battery') }} %."

    # Ikea Switch 2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 2 is {{ states('sensor.ikea_switch_2_battery') }} %."

    # Ikea Switch 5
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_switch_5_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the Ikea switch 5 is {{ states('sensor.ikea_switch_5_battery') }} %."

    # Motion sensor in the workroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_workroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the workroom is {{ states('sensor.motion_workroom_battery') }} %."

    # Motion sensor upstairs
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_upstairs_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor upstairs is {{ states('sensor.motion_upstairs_battery') }} %."

    # Motion sensor in the guestroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_guestroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the guestroom is {{ states('sensor.motion_guestroom_battery') }} %."

    # Motion sensor in the bedroom
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_bedroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the bedroom is {{ states('sensor.motion_bedroom_battery') }} %."

    # Motion sensor in the kitchen
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_kitchen_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the kitchen is {{ states('sensor.motion_kitchen_battery') }} %."

    # Motion sensor in the living room
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_livingroom_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the living room is {{ states('sensor.motion_livingroom_battery') }} %."

    # Motion sensor in the entrance
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.motion_entrance_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the motion sensor in the entrance is {{ states('sensor.motion_entrance_battery') }} %."

    # Keypad 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.keypad_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the keypad 1 is {{ states('sensor.keypad_1_battery') }} %."

    # IKEA on/off switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_on_off_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA on/off switch 1 is {{ states('sensor.ikea_on_off_switch_1_battery') }} %."
    
    # IKEA up/down switch 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 1 is {{ states('sensor.ikea_up_down_switch_1_battery') }} %."
    
    # IKEA up/down switch 2
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_2_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 1 is {{ states('sensor.ikea_up_down_switch_2_battery') }} %."

    # IKEA up/down switch 3
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.ikea_up_down_switch_3_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the IKEA up/down switch 1 is {{ states('sensor.ikea_up_down_switch_3_battery') }} %."

    # TuYa weather sensor 1
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.entity_id == 'sensor.tuya_weather_1_battery' }}"
      sequence:
      - service: notify.pushover
        data_template:
          title: "Low battery"
          message: "The battery of the TuYa weather sensor 1 is {{ states('sensor.tuya_weather_1_battery') }} %."

    default:
    - service: notify.pushover
      data_template:
        title: "Low battery"
        message: "The battery of {{ trigger.to_state.entity_id }} is {{ trigger.to_state.state }} %."




