- alias: "[Bedroom] Turn on bed light after sunset"
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_2"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'single' }}"
  - condition: sun
    after: sunset
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led
    data:
      rgb_color: [255, 63, 0]
      brightness_pct: 100


- alias: "[Bedroom] Turn on bed light before sunrise"
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_2"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'single' }}"
  - condition: sun
    before: sunrise
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led
    data:
      rgb_color: [255, 63, 0]
      brightness_pct: 100


- alias: "[Bedroom] Turn on bed light in daylight"
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_2"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'single' }}"
  - condition: sun
    after: sunrise
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led


- alias: "[Bedroom] Turn off bed light"
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_2"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'single' }}"
  - condition: state
    entity_id: light.bed_led
    state: 'on'
  action:
  - service: timer.cancel
    entity_id: timer.bed_light_timer
  - service: light.turn_off
    entity_id: light.bed_led


- alias: "[Bedroom] Random color on double click"
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_2"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'double' }}"
  - condition: state
    entity_id: light.bed_led
    state: 'on'
  action:
  - service: python_script.generate_color
    entity_id: light.bed_led

