- alias: "[Bedroom] Bed LED sunrise"
  initial_state: true
  trigger:
  - platform: time
    at: "06:50:00"
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_bedroom
    below: 20
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'disarmed'
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'armed_night'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led
    data:
      rgb_color: [255, 255, 0]
      transition: 600


- alias: "[Bedroom] Color loop over bed light"
  initial_state: false
  trigger:
  - platform: time_pattern
    seconds: '/3'
  action:
  - service: python_script.color_loop
    data:
      entity_id: light.bed_led
