# Ikea switch 2

- alias: '[Bedroom] Turn on light'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'off'
  action:
  - service: light.turn_on
    data:
      color_temp: 380
      entity_id: light.gledopto_lamp_4


- alias: '[Bedroom] Turn off light'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.gledopto_lamp_4


    
- alias: "[Bedroom] Increase brightness"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 2002
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'on'
  action:
  - service: light.turn_on
    data_template: 
      entity_id: light.gledopto_lamp_4
      brightness: '{{ states.light.gledopto_lamp_4.attributes.brightness + 75 }}'

- alias: "[Bedroom] Decrease brightness"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 3002
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'on'
  action:
  - service: light.turn_on
    data_template: 
      entity_id: light.gledopto_lamp_4
      brightness: '{{ states.light.gledopto_lamp_4.attributes.brightness - 75 }}'


- alias: "[Bedroom] Set max brightness"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 2001
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.gledopto_lamp_4
    data_template: 
      brightness_pct: 100

- alias: "[Bedroom] Set min brightness"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 3001
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_4
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.gledopto_lamp_4
    data_template: 
      brightness_pct: 5



