- alias: "[Bedroom] Turn on bed light after sunset"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_bedroom
      event: 1002
  condition:
  - condition: sun
    after: sunset
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led
    data:
      rgb_color: [255, 63, 0]
      brightness_pct: 100


- alias: "[Bedroom] Turn on bed light before sunrise"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_bedroom
      event: 1002
  condition:
  - condition: sun
    before: sunrise
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led
    data:
      rgb_color: [255, 63, 0]
      brightness_pct: 100


- alias: "[Bedroom] Turn on bed light in daylight"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_bedroom
      event: 1002
  condition:
  - condition: sun
    after: sunrise
  - condition: state
    entity_id: light.bed_led
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_led


- alias: "[Bedroom] Turn off bed light"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_bedroom
      event: 1002
  condition:
  - condition: state
    entity_id: light.bed_led
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bed_led


- alias: "[Bedroom] Random color on double click"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_bedroom
      event: 1004
  condition:
  - condition: state
    entity_id: light.bed_led
    state: 'on'
  action:
  - service: python_script.generate_color
    entity_id: light.bed_led

