# Ikea switch 2

- alias: '[Bedroom] Toggle light'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.bulb_13


- alias: "[Bedroom] Increase brightness to maximum"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      #event: 2001 # press and hold the button "light up"
      event: 2002  # press the button "light up"
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness_pct: 100

- alias: "[Bedroom] Decrease brightness to minimum"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      #event: 3001 # press and hold the button "light down"
      event: 3002  # press the button "light down"
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness_pct: 5

