# Ikea switch 2

- alias: 'Toggle bedroom light'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.bulb_13


#- alias: 'Turn on bedroom'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 1002
#  condition:
#  - condition: state
#    entity_id: light.bulb_13
#    state: 'off'
#  action:
#  - service: light.turn_on
#    entity_id: light.bulb_13
#
#- alias: 'Turn off bedroom'
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 1002
#  condition:
#  - condition: state
#    entity_id: light.bulb_13
#    state: 'on'
#  action:
#  - service: light.turn_off
#    entity_id: light.bulb_13

#---------------------------------------
#- alias: "Increase brightness bedroom"
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 2002
#  action:
#  - service: light.turn_on
#    entity_id: light.bulb_13
#    data_template: 
#      brightness: '{{ states.light.bulb_13.attributes.brightness + 25 }}'
#
#
#- alias: "Decrease brightness bedroom"
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 3002
#  action:
#  - service: light.turn_on
#    entity_id: light.bulb_13
#    data_template: 
#      brightness: '{{ states.light.bulb_13.attributes.brightness - 25 }}'

- alias: "Increase brightness bedroom to maximum"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      #event: 2001 # press and hold the button "light up"
      event: 2002  # press the button "light up"
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness_pct: 100

- alias: "Decrease brightness bedroom to minimum"
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      #event: 3001 # press and hold the button "light down"
      event: 3002  # press the button "light down"
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness_pct: 5

