- alias: "[Bedroom Blinds Right] Run script on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right

# ------------------

- alias: "[Bedroom Blinds Right] Set moving sensor to 0 when it's down"
  trigger:
  - platform: numeric_state
    entity_id: cover.blinds_bedroom_right
    value_template: "{{ state.attributes.current_position }}"
    below: 3 # 0 is min
    for:
      seconds: 1
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_bedroom_right_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'off'


- alias: "[Bedroom Blinds Right] Set moving sensor to 0 when it's up"
  trigger:
  - platform: numeric_state
    entity_id: cover.blinds_bedroom_right
    value_template: "{{ state.attributes.current_position }}"
    above: 97 # 100 is max
    for:
      seconds: 1
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_bedroom_right_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'off'

# ------------------

- alias: '[Bedroom Blinds Right] Go up'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "open" }}'
  - condition: state
    entity_id: binary_sensor.blinds_bedroom_right_moving
    state: 'off'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'on'
  - service: cover.set_cover_position
    data:
      entity_id: cover.blinds_bedroom_right
      position: 100


- alias: '[Bedroom Blinds Right] Go down'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "down" }}'
  - condition: state
    entity_id: binary_sensor.blinds_bedroom_right_moving
    state: 'off'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'on'
  - wait_template: "{{ states('binary_sensor.blinds_bedroom_right_moving')|string == 'on' }}"
    timeout: '00:02:00'
    continue_on_timeout: false
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_bedroom_right


- alias: '[Bedroom Blinds Right] Stop moving'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: state
    entity_id: binary_sensor.blinds_bedroom_right_moving
    state: 'on'
  action:
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_bedroom_right
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'off'

# ------------------

- alias: '[Bedroom Blinds Right] Go up while holding'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "open" }}'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'on'
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_bedroom_right


- alias: '[Bedroom Blinds Right] Stop moving on release'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "stop" }}'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'off'
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_bedroom_right


- alias: '[Bedroom Blinds Right] Go down while holding'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_2"
  condition:
  - condition: template
    value_template: '{{ trigger.payload_json.action == "close" }}'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_bedroom_right
      is_moving: 'on'
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_bedroom_right

