
- alias: '[Camera Foscam1] Take snapshot'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.foscam1_snapshot
    to: 'on'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_1
      filename: '/home/homeassistant/.homeassistant/media/Snapshots/Foscam1_{{ now().strftime("%Y%m%d-%H%M%S") }}_m.jpg'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.foscam1_snapshot


- alias: '[Camera Foscam1] Restart power if unavailable'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.foscam1
    to: 'off'
    for:
      minutes: 5
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.ikea_plug_3
  - delay:
      seconds: 5
  - service: switch.turn_on
    data:
      entity_id: switch.ikea_plug_3
#  - service: notify.pushover
#    data:
#      message: "Foscam1 is unavailable. Restart power."


- alias: '[Camera Foscam1] Record video'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.foscam1_record_video
    to: 'on'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_1
      filename: '/home/homeassistant/.homeassistant/media/Records/Foscam1_{{ now().strftime("%Y%m%d-%H%M%S") }}_m.mp4'
      duration: "{{ states('input_number.foscam1_record_length') | int }}"
  - delay:
      seconds: "{{ states('input_number.foscam1_record_length') | int }}"
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.foscam1_record_video



