#- alias: '[Camera] Set sensitivity for Foscam1'
#  hide_entity: true
#  initial_state: true
#  trigger:
#  - platform: state
#    entity_id: input_select.foscam1_motion_sensitivity
#  action:
#  - service: python_script.foscam_config
#    data:
#      action: 'sensitivity'
#      ip: !secret foscam1_ip
#      username: !secret foscam1_username
#      password: !secret foscam1_password
#      input_select: 'input_select.foscam1_motion_sensitivity'


#  trigger:
#  - platform: state
#    entity_id: input_select.foscam1_motion_sensitivity


- alias: '[Camera] Take a snapshot on detected motion'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.foscam_1_motion
    to: 'on'
  action:
  - service: script.take_snapshots
    data_template:
      camera: camera.foscam_1
      name: "Foscam1"
      detect_time: '{{ now().strftime("%Y%m%d-%H%M%S") }}'
  - service: notify.pushover
    data:
      message: "Foscam1: Motion detected."

#  - service: notify.pushover
#    data_template:
#      title: "Alarm"
#      message: "Motion detected! A snapshot taken"
#      data:
#        file:
#          path: '/home/homeassistant/snapshots/foscam1_motion.jpg'
#      message: "Sensitivity: {{ states.input_select.foscam1_motion_sensitivity.state.split('-')[1] }}"
