# https://www.home-assistant.io/docs/ecosystem/certificates/lets_encrypt/
# sensor.ssl_certificate_expiry

- alias: '[HASS Certificate] Notification on update'
  initial_state: true
  trigger:
  - platform: template
    value_template: >
      '{{ states.sensor.ssl_certificate_expiry.state | int  <= 10 }}'
  action:
  - service: notify.pushover
    data_template:
      title: "Hass Certificate"
      message: "Home Assistant's certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days."


#- alias: '[HASS Certificate] Auto Renew'
#  trigger:
#  - platform: numeric_state
#    entity_id: sensor.ssl_cert_expiry
#    below: 20
#  action:
#  - service: shell_command.renew_ssl
