# sensor.ssl_certificate_expiry

- alias: 'Home Assistant Certificate Notification'
  initial_state: 'on'
  trigger:
    platform: template
    value_template: >
      {{ states.sensor.ssl_certificate_expiry.state | int  <= 10 }}
  condition:
    condition: template
    value_template: >
      {{ states.sensor.ssl_certificate_expiry.state != "unknown" }}
  action:
    service: notify.pushover
    data_template:
      message: >
        Home Assistant's certificate expires in {{ states.sensor.ssl_certificate_expiry.state }} days.

