
- alias: '[Christmas Lights] Turn on outdoor lights at sunset'
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.tuya_power_1


- alias: '[Christmas Lights] Turn off outdoor lights at sunrise'
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: switch.turn_off
    entity_id: switch.tuya_power_1

