
- alias: '[Christmas Lights] Turn on outdoor lights at sunset'
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.tuya_power_1
  - service: switch.turn_on
    entity_id: switch.xiaomi_relay_1_l2
  - service: shell_command.christmas_tree_start
  - service: automation.turn_on
    entity_id: automation.christmas_lights_christmas_tree_animations


- alias: '[Christmas Lights] Turn off outdoor lights at sunrise'
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: switch.turn_off
    entity_id: switch.tuya_power_1
  - service: switch.turn_off
    entity_id: switch.xiaomi_relay_1_l2
  - service: automation.turn_off
    entity_id: automation.christmas_lights_christmas_tree_animations
  - service: shell_command.christmas_tree_stop

#--------------------------------------------------------

- alias: '[Christmas Lights] Turn on indoor lights at sunset'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
  - service: switch.turn_on
    entity_id: switch.ikea_plug_7
  - service: switch.turn_on
    entity_id: switch.wifi_cord

- alias: '[Christmas Lights] Turn off indoor lights at sunrise'
  trigger:
  - platform: sun
    event: sunrise
    offset: '00:30:00'
  action:
  - service: switch.turn_off
    entity_id: switch.ikea_plug_7
  - service: switch.turn_off
    entity_id: switch.wifi_cord

#--------------------------------------------------------
#
- alias: '[Christmas lights] Turn off Stjärnor when all in bed'
  trigger:
  - platform: state
    entity_id: binary_sensor.all_in_bed
    to: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.ikea_plug_7

- alias: '[Christmas lights] Turn on Stjärnor when awake'
  trigger:
  - platform: state
    entity_id: binary_sensor.all_in_bed
    to: 'off'
  condition:
  - condition: sun
    before: sunrise
  action:
  - delay: "00:00:30"
  - service: switch.turn_on
    entity_id: switch.ikea_plug_7

#--------------------------------------------------------


- alias: '[Christmas lights] Christmas tree animations'
  trigger:
  - platform: time_pattern
    minutes: '/3'
    seconds: 00
  action:
  - service: shell_command.christmas_tree_effects

