#########################################################
#
# Close the covers when it get dark
#
#########################################################
- alias: "[Cover Workroom] Close cover when it gets dark"
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_illuminance_1
    below: 10
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.workroom_close_blinds_automation
    state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_workroom


- alias: "[Cover Guestroom] Close cover when it gets dark"
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_illuminance_1
    below: 10
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.guestroom_close_blinds_automation
    state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_guestroom


- alias: "[Cover Bedroom] Close cover when it gets dark"
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_illuminance_1
    below: 10
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.bedroom_blinds_auto
    state: 'on'
  action:
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_bedroom_left
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_bedroom_right


#########################################################
#
# Open the covers when it get bright and 
# at least one person is not sleeping
#
#########################################################
- alias: "[Cover Workroom] Open cover when it gets bright"
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_illuminance_1
    above: 10
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.workroom_open_blinds_automation
    state: 'on'
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_workroom


- alias: "[Cover Guestroom] Open cover when it gets bright"
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.xiaomi_illuminance_1
    above: 10
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: input_boolean.guestroom_open_blinds_automation
    state: 'on'
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  action:
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_guestroom


#########################################################
#
# Open the covers when someone has waken up and it's brght
#
#########################################################
- alias: "[Cover Workroom] Open cover when someone wakes up"
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: 'armed_night'
    to: 'disarmed'
  condition:
  - condition: state
    entity_id: input_boolean.workroom_open_blinds_automation
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.xiaomi_illuminance_1
    above: 10
  action:
  - delay:
      seconds: 10
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_workroom


- alias: "[Cover Guestroom] Open cover when someone wakes up"
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: 'armed_night'
    to: 'disarmed'
  condition:
  - condition: state
    entity_id: input_boolean.guestroom_open_blinds_automation
    state: 'on'
  - condition: numeric_state
    entity_id: sensor.xiaomi_illuminance_1
    above: 10
  action:
  - delay:
      seconds: 10
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_guestroom

