- alias: "[deCONZ] New Version available"
  trigger:
  - platform: state
    entity_id: sensor.deconz_available_version
  action:
  - service: notify.pushover
    data_template:
      title: "ZigBee"
      message: "deCONZ version {{ states.sensor.deconz_available_version.state }} is available!"

