
- alias: '[Doorbell] Sound if button pressed'
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
  - service: shell_command.doorbell_sound


#-----------------------------

- alias: '[Doorbell] Xiaomi button pressed'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_button_1"
  condition:
  - condition: template
    value_template: "{{ trigger.payload_json.action == 'single' }}"
  action:
  - service: script.turn_on
    data:
      entity_id: script.doorbell


