
- alias: '[Doorbell] Sound if button pressed'
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    to: 'on'
  action:
  - service: shell_command.doorbell_sound


#-----------------------------

- alias: '[Doorbell] Xiaomi button pressed'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_workroom 
      #event: 1002 #-short press
      #event: 1001 # press and hold
      #event: 1004 # long press
  action:
  - service: script.turn_on
    data:
      entity_id: script.doorbell


