- alias: "Toggle WiFi cord to off"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002130dec
      click_type: single
  condition:
  - condition: state
    entity_id: switch.wifi_cord_1
    state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.wifi_cord_1

- alias: "Toggle WiFi cord to on"
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0002130dec
      click_type: single
  condition:
  - condition: state
    entity_id: switch.wifi_cord_1
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.wifi_cord_1

