
- alias: '[Entrance light] Turn on when the door opens'
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_entrance
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_entrance
    below: 10
  - condition: state
    entity_id: light.ikea_lamp_2
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_2
    data:
      brightness_pct: 100
      transition: 3
  - service: automation.turn_on
    entity_id: automation.entrance_light_turn_off_in_5_min_after_last_motion


- alias: '[Entrance light] Turn off in 5 min after last motion' 
  initial_state: 'off'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_entrance
    to: 'off'
    for:
      minutes: 5
  action:
  - service: automation.turn_off
    entity_id: automation.entrance_light_turn_off_in_5_min_after_last_motion
  - service: light.turn_off
    entity_id: light.ikea_lamp_2



