- alias: '[Entrance] Door sound'
  initial_state: True
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_entrance
    to: "on"
  action:
  - service: shell_command.entrance_door_open

