- alias: '[Entrance light] Force to update västtrafik sensor'
  hide_entity: true
  trigger:
  - platform: time_pattern
    minutes: '/1'
    seconds: 00
  condition:
  - condition: time
    after:  '07:10:00'
    before: '07:50:00'
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: template
    value_template: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M")) == states.sensor.vasttrafik_linje_176_mot_lindholmen.state }}'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - delay: '00:01:00'
  - service: homeassistant.update_entity
    entity_id: sensor.vasttrafik_linje_176_mot_lindholmen
  - service: homeassistant.update_entity
    entity_id: sensor.vasttrafik_linje_177_mot_lindholmen


- alias: '[Entrance light] Turn on at 7:18'
  hide_entity: true
  trigger:
  - platform: time
    at: "07:18:00"
  condition:
  # (the illumination sensor at the entrance shows a value below 30) AND (it's a work day) AND (the alarm is not on)
  - condition: numeric_state
    entity_id: sensor.lightlevel_entrance
    below: 12
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: light.ikea_lamp_2
    state: 'off'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_2
    data:
      brightness_pct: 100
      transition: 3


- alias: '[Entrance light] Turn off at 7:45 if no motion'
  hide_entity: true
  trigger:
  - platform: time
    at: "07:45:00"
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: light.ikea_lamp_2
    state: 'on'
  - condition: state
    entity_id: binary_sensor.presence_entrance
    state: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    entity_id: light.ikea_lamp_2
    data:
      transition: 3


- alias: '[Entrance light] Turn on when the door opens'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_entrance
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_entrance
    below: 10
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_2
    data:
      brightness_pct: 100
      transition: 3


- alias: '[Entrance light] Turn off in 5 minutes after the door is closed'
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.openclose_entrance
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    entity_id: light.ikea_lamp_2

