- alias: 'Entrance light before the buss'
  hide_entity: true
  initial_state: true
  trigger:
    # If it's 10 mins (600 secs) to the next 176 bus
    - platform: template
      value_template: '{{ ((as_timestamp(now()) + 600 ) | timestamp_custom("%H:%M")) == states.sensor.vasttrafik_linje_176_mot_lindholmen.state }}'
  condition:
    # (Time is between 07:20 - 07:50) AND (the illumination sensor at the entrance shows a value below 30) AND (it's a work day) AND (the alarm is not on)
    - condition: time
      after:  '07:20:00'
      before: '07:50:00'
    - condition: numeric_state
      entity_id: sensor.illumination_158d000236a817
      below: 30
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
    - condition: state
      entity_id: alarm_control_panel.house
      state: 'disarmed'
    - condition: state
      entity_id: light.bulb_16
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.bulb_16
      data:
        brightness_pct: 100
        #kelvin: 2700
      #  rgb_color: [255, 255, 255]


- alias: 'Entrance light is on when the door is open'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d000238694e
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.illumination_158d000236a817
    below: 10
  action:
  - service: light.turn_on
    entity_id: light.bulb_16
    data:
      brightness_pct: 100
      transition: 3


- alias: 'Turn off the entrance light in 5 minutes after the door was closed'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.door_window_sensor_158d000238694e
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
  - service: light.turn_off
    entity_id: light.bulb_16
