
- alias: '[Front Yard] Light if motion after sunset'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: light.turn_on
    entity_id: light.frontyard


- alias: '[Front Yard] Turn off light if no motion for 1 min'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_frontyard
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: light.frontyard
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.frontyard


- alias: '[Front Yard] Notify if motion after sunset'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: notify.pushover
    data_template:
      title: "Frontyard motion"
      message: "Motion detected in the frontyard"
