- alias: '[Garden Lights] Turn on at sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:00:00'
  condition:
  - condition: state
    entity_id: light.garden_lights_1
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.garden_lights_1
      transition: 10
      brightness_pct: 100
      rgb_color: [255, 255, 255]
  - delay: '00:00:12'
  - service: light.turn_on
    data:
      entity_id: light.garden_lights_1
      effect: "RandomColorLamp"


- alias: '[Garden Lights] Turn off at sunrise'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunrise
    offset: '-00:30:00'
  condition:
  - condition: state
    entity_id: light.garden_lights_1
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.garden_lights_1

