
- alias: '[Guestroom Blinds] Switch automation'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_3"
  action:
  - choose:

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'open' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'close' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'stop' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_guestroom


- alias: '[Guestroom Blinds] Switch automation (IKEA Switch)'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_switch_1"
  action:
  - choose:

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'brightness_up_click' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'brightness_down_click' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'toggle' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_guestroom

 
