- alias: '[Guestroom Blinds] Request position after restart'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: '00:00:30'
  - service: mqtt.publish
    data_template:
      topic: 'zigbee2mqtt/blinds_guestroom/get'
      payload: '{"position":""}'
      retain: false
      qos: 0


- alias: '[Guestroom Blinds] Switch automation'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_up_down_switch_3"
  action:
  - choose:

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'open' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'close' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_guestroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'stop' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_guestroom

 
