- alias: "[HASS] Notification on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: notify.pushover
    data:
      message: "Home Assistant has started"

- alias: "[HASS] Notification on stop"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: shutdown
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: notify.pushover
    data:
      message: "Home Assistant has stopped"

- alias: "[HASS] New Version available"
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hass_available_version
  action:
  - service: notify.pushover
    data:
      message: "Home Assistant version {{ states.sensor.hass_available_version.state }} is available!"
