- alias: 'Turn on bedroom'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  condition:
  - condition: state
    entity_id: light.bulb_13
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bulb_13

- alias: 'Turn off bedroom'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 1002
  condition:
  - condition: state
    entity_id: light.bulb_13
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bulb_13


- alias: "Increase brightness bedroom"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 2002
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness: '{{ states.light.bulb_13.attributes.brightness + 25 }}'


- alias: "Decrease brightness bedroom"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_2
      event: 3002
  action:
  - service: light.turn_on
    entity_id: light.bulb_13
    data_template: 
      brightness: '{{ states.light.bulb_13.attributes.brightness - 25 }}'


#- alias: "Increase temperature bedroom"
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 5002
#  action:
#  - service: light.turn_on
#    entity_id: light.bulb_13
#    data_template: 
#      kelvin: '{{ states.light.bulb_13.attributes.kelvin + 500 }}'
#
#
#- alias: "Decrease temperature bedroom"
#  trigger:
#    platform: event
#    event_type: deconz_event
#    event_data:
#      id: ikea_switch_2
#      event: 4002
#  action:
#  - service: light.turn_on
#    entity_id: light.bulb_13
#    data_template: 
#      kelvin: '{{ states.light.bulb_13.attributes.kelvin - 500 }}'

