- alias: '[Keypad1] Button actions'
  trigger:
    platform: mqtt
    topic: "zigbee2mqtt/keypad_1"
  #mode: queued
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_1_single' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_5_single' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_4_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 20
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_3_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 60
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_2_single' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_8_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 40
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_7_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 80
          entity_id: cover.blinds_bedroom_left

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_6_single' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_bedroom_left

    #---
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_14_single' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_18_single' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_13_single' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_17_single' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_16_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 20
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_20_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 40
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_15_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 60
          entity_id: cover.blinds_bedroom_right

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action | string == 'button_19_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 80
          entity_id: cover.blinds_bedroom_right
