- alias: '[Keypad1] Button actions'
  trigger:
    platform: mqtt
    topic: "zigbee2mqtt/keypad_1/action"
  #mode: queued
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_1_single' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_5_single' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_4_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 0
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_3_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 40
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_2_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 80
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_8_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 20
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_7_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 60
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload | string == 'button_6_single' }}"
      sequence:
      - service: cover.set_cover_position
        data:
          position: 100
          entity_id: cover.blinds_workroom
