- alias: '[Kitchen] Opple Switch'
  initial_state: true
  mode: parallel
  max: 2
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_oppleswitch_1"
  action:
  - service: python_script.opple_switch_kitchen
    data_template:
      action: "{{ trigger.payload_json.action }}"

