- alias: '[Kitchen] Opple Switch'
  initial_state: true
  mode: parallel
  max: 2
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: opple_switch_1
  action:
  - service: python_script.opple_switch_kitchen
    data_template:
      event: "{{ trigger.event }}"

