
- alias: '[Kitchen] Turn off all lights'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.ikea_lamp_4
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_5
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_6
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_7
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_8
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_9
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.kitchen_lights_1
  - service: light.turn_off
    entity_id: light.kitchen_lights_2


- alias: '[Kitchen] Turn on all lights'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 1002
  condition:
  - condition: state
    entity_id: light.ikea_lamp_4
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_5
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_6
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_7
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_8
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_9
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data:
      kelvin: 3200
  - service: light.turn_on
    entity_id: light.kitchen_lights_2


- alias: "[Kitchen] Toggle lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 4002
  action:
  - service: light.toggle
    entity_id: light.kitchen_lights_1


- alias: "[Kitchen] Toggle lights 2"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 5002
  action:
  - service: light.toggle
    entity_id: light.kitchen_lights_2


- alias: "[Kitchen] Decrease brightness for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 3002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      brightness: '{{ states.light.kitchen_lights_1.attributes.brightness - 75 }}'

- alias: "[Kitchen] Decrease brightness for lights 2"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 3002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_2
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_2
    data_template: 
      brightness: '{{ states.light.kitchen_lights_2.attributes.brightness - 75 }}'


- alias: "[Kitchen] Increase brightness for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 2002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      brightness: '{{ states.light.kitchen_lights_1.attributes.brightness + 75 }}'

- alias: "[Kitchen] Increase brightness for lights 2"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 2002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_2
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_2
    data_template: 
      brightness: '{{ states.light.kitchen_lights_2.attributes.brightness + 75 }}'
