
- alias: '[Kitchen] Turn off lights 1'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.ikea_lamp_4
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_5
      state: 'on'
    - condition: state
      entity_id: light.ikea_lamp_6
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.kitchen_lights_1


- alias: '[Kitchen] Turn on lights 1'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 1002
  condition:
  - condition: state
    entity_id: light.ikea_lamp_4
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_5
    state: 'off'
  - condition: state
    entity_id: light.ikea_lamp_6
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data:
      kelvin: 3200


- alias: "[Kitchen] Decrease color temperature for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 4002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      color_temp: '{{ states.light.kitchen_lights_1.attributes.color_temp - 50 }}'


- alias: "[Kitchen] Increase color temperature for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 5002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      color_temp: '{{ states.light.kitchen_lights_1.attributes.color_temp + 50 }}'


- alias: "[Kitchen] Decrease brightness for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 3002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      brightness: '{{ states.light.kitchen_lights_1.attributes.brightness - 75 }}'


- alias: "[Kitchen] Increase brightness for lights 1"
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_3
      event: 2002
  condition:
  - condition: state
    entity_id: light.kitchen_lights_1
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.kitchen_lights_1
    data_template: 
      brightness: '{{ states.light.kitchen_lights_1.attributes.brightness + 75 }}'

