- alias: '[Living room] Ikea switch 3'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_switch_3"
  action:
  - service: python_script.ikea_switch_living_room
    data_template:
      button: '{{ trigger.payload_json.action }}'

