
- alias: '[Living room] Wallswitch'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/xiaomi_wallswitch_1"
  action:
  - choose:
    # Turn on the living room lights
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'single_right' }}"
      - condition: state
        entity_id: light.gledopto_lamp_1
        state: 'off'
      - condition: state
        entity_id: light.gledopto_lamp_2
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.gledopto_lamp_1
        data:
          color_temp: 380
      - service: light.turn_on
        entity_id: light.gledopto_lamp_2
        data:
          color_temp: 380
    # Turn off living room lights
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'single_right' }}"
      - condition: or
        conditions:
        - condition: state
          entity_id: light.gledopto_lamp_1
          state: 'on'
        - condition: state
          entity_id: light.gledopto_lamp_2
          state: 'on'
      sequence:
      - service: light.turn_off
        entity_id: light.gledopto_lamp_1
      - service: light.turn_off
        entity_id: light.gledopto_lamp_2
    # Toggle entrance light
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'single_left' }}"
      sequence:
      - service: light.toggle
        entity_id: light.ikea_lamp_2
    # Turn on Ball light
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'hold_left' }}"
      - condition: state
        entity_id: light.ikea_lamp_3
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.ikea_lamp_3
        data:
          brightness: 255
          rgb_color: [255, 205, 120]
    # Turn off Ball light 
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'hold_left' }}"
      - condition: state
        entity_id: light.ikea_lamp_3
        state: 'on'
      sequence:
      - service: light.turn_off
        entity_id: light.ikea_lamp_3
        data:
          transition: 2
    # Turn on Mood lamp in Colorloop
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'hold_right' }}"
      - condition: state
        entity_id: light.mood_lamp
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.mood_lamp
        data:
          brightness_pct: 85
          effect: "Colorloop"
    # 
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'hold_right' }}"
      - condition: state
        entity_id: light.mood_lamp
        state: 'on'
      sequence:
      - service: light.turn_off
        entity_id: light.mood_lamp
    # 
    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'double_right' }}"
      - condition: state
        entity_id: light.mood_lamp
        state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.mood_lamp
        data_template:
          effect: '{% if states.light.mood_lamp.attributes.effect == "Fire" %}
                     Sparkles
                   {% elif states.light.mood_lamp.attributes.effect == "Sparkles" %}
                     Rainbow
                   {% elif states.light.mood_lamp.attributes.effect == "Rainbow" %}
                     Colorloop
                   {% elif states.light.mood_lamp.attributes.effect == "Colorloop" %}
                     Chaos
                   {% elif states.light.mood_lamp.attributes.effect == "Chaos" %}
                     PlasmaLamp
                   {% else %}
                     Fire
                   {% endif %}'
    # 
    #- conditions:
    #  - condition: template
    #    value_template: "{{ trigger.payload_json.action == 'hold_both' }}"
    #  sequence:

##################
