- alias: '[MoodLamp] Turn on when disarmed after sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      effect: "Rainbow"


- alias: '[MoodLamp] Turn off when disarmed before sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  condition:
  - condition: sun
    before: sunset
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      rgb_color: [255, 255, 255]
  - delay:
      seconds: 1
  - service: light.turn_off
    entity_id: light.mood_lamp


- alias: '[MoodLamp] Police effect while pending'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'pending'
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      effect: "Alarm"


- alias: '[MoodLamp] Turn on if motion at night'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_entrance
    to: 'on'
  - platform: state
    entity_id: binary_sensor.presence_livingroom
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_livingroom
    below: 10
  - condition: state
    entity_id: light.mood_lamp
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: media_player.sirius
    state: 'off'
  - condition: time
    after: "00:01"
    before: "08:00"
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      effect: "Chaos"


- alias: '[MoodLamp] Turn off if no motion at night'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_livingroom
    from: 'on'
    to: 'off'
    for:
      seconds: 180
  condition:
  - condition: state
    entity_id: light.mood_lamp
    state: 'on'
  - condition: state
    entity_id: media_player.sirius
    state: 'off'
  - condition: time
    after: "00:01"
    before: "08:05"
  action:
  - service: light.turn_off
    entity_id: light.mood_lamp


- alias: '[MoodLamp] Turn on at sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:00:00'
  condition:
  - condition: state
    entity_id: light.mood_lamp
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
#  - condition: state
#    entity_id: input_boolean.vacation_mode
#    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      brightness_pct: 85
      effect: "Colorloop"


- alias: '[MoodLamp] Turn on at sunset if vacation away'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:00:00'
  condition:
  - condition: state
    entity_id: light.mood_lamp
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      effect: "Chaos"


- alias: '[MoodLamp] Turn off at midnight'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: time
    at: "23:59:00"
  action:
  - service: light.turn_off
    entity_id: light.mood_lamp


