# The bulb closer to the kitchen is the left light - bulb_14
# The bulb closer to the window is the right light - bulb_12
#
- alias: 'Turn on all lights in the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.bulb_12
      state: 'off'
    - condition: state
      entity_id: light.bulb_14
      state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12
    data:
      kelvin: 3200
  - service: light.turn_on
    entity_id: light.bulb_14
    data:
      kelvin: 3200

- alias: 'Turn off all lights the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 1002
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: light.bulb_12
      state: 'on'
    - condition: state
      entity_id: light.bulb_14
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bulb_12
  - service: light.turn_off
    entity_id: light.bulb_14



- alias: 'Turn on the left light in the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 4002
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bulb_14

- alias: 'Turn off the left light in the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 4002
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bulb_14



- alias: 'Turn on the right light in the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 5002
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12

- alias: 'Turn off the right light in the living room'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 5002
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bulb_12
    


- alias: "Increase brightness of the right light in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 2002
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12
    data_template: 
      brightness: '{{ states.light.bulb_12.attributes.brightness + 50 }}'

- alias: "Decrease brightness of the right light in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 3002
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12
    data_template: 
      brightness: '{{ states.light.bulb_12.attributes.brightness - 50 }}'
        


- alias: "Increase brightness of the left light in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 2002
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_14
    data_template: 
      brightness: '{{ states.light.bulb_14.attributes.brightness + 50 }}'

- alias: "Decrease brightness of the left light in the living room"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 3002
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_14
    data_template: 
      brightness: '{{ states.light.bulb_14.attributes.brightness - 50 }}'



- alias: "The right light brightness in the living room to maximum"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 2001
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12
    data_template: 
      brightness_pct: 100

- alias: "The right light brightness in the living room to minimum"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 3001
  condition:
  - condition: state
    entity_id: light.bulb_12
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_12
    data_template: 
      brightness_pct: 5



- alias: "The left light brightness in the living room to maximum"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 2001
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_14
    data_template: 
      brightness_pct: 100

- alias: "The left light brightness in the living room to minimum"
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_1
      event: 3001
  condition:
  - condition: state
    entity_id: light.bulb_14
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bulb_14
    data_template: 
      brightness_pct: 5
