- alias: '[Logger] Switch loglevel for pyhton scripts to debug'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_python_script
    to: 'on'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.python_script: debug

- alias: '[Logger] Switch loglevel for pyhton scripts to warning'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_python_script
    to: 'off'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.python_script: warning

#---------------------------- deconz

- alias: '[Logger] Switch loglevel for deconz to debug'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_deconz
    to: 'on'
  action:
  - service: logger.set_level
    data:
      pydeconz: debug
      homeassistant.components.deconz: debug

- alias: '[Logger] Switch loglevel for deconz to warning'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_deconz
    to: 'off'
  action:
  - service: logger.set_level
    data:
      pydeconz: warning
      homeassistant.components.deconz: warning

#---------------------------- mqtt
 
- alias: '[Logger] Switch loglevel for mqtt to debug'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_mqtt
    to: 'on'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.mqtt: debug

- alias: '[Logger] Switch loglevel for mqtt to warning'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_mqtt
    to: 'off'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.mqtt: warning


#---------------------------- shell commands

- alias: '[Logger] Switch loglevel for shell commands to debug'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_shell_commands
    to: 'on'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.shell_command: debug

- alias: '[Logger] Switch loglevel for shell commands to warning'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_shell_commands
    to: 'off'
  action:
  - service: logger.set_level
    data:
      homeassistant.components.shell_command: warning


#---------------------------- helpers.script

- alias: '[Logger] Switch loglevel for helpers.script to debug'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_helpers_script
    to: 'on'
  action:
  - service: logger.set_level
    data:
      homeassistant.helpers.script: debug

- alias: '[Logger] Switch loglevel for helpers.script to warning'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.logger_helpers_script
    to: 'off'
  action:
  - service: logger.set_level
    data:
      homeassistant.helpers.script: warning
