- alias: '[Guest room] Turn on light on motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_room
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_room
    below: 10
  action:
  - service: light.turn_on
    entity_id: light.gledopto_lamp_3
    data:
      color_temp: 400
#      transition: 5
#      brightness: 255

- alias: '[Guest room] Turn off light in 5 minutes after motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_room
    from: 'on'
    to: 'off'
    for:
      seconds: 300
  condition:
  - condition: state
    entity_id: light.gledopto_lamp_3
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.gledopto_lamp_3
#    data:
#      transition: 5
