- alias: 'Turn on room light on movement'
  initial_state: true
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_room
    from: 'off'
    to: 'on'
  condition:
  - condition: numeric_state
    entity_id: sensor.lightlevel_room
    below: 10
  action:
  - service: light.turn_on
    entity_id: light.bulb_17
    data:
      brightness_pct: 100
      transition: 5

- alias: 'Turn off room light in 5 minutes'
  initial_state: true
  hide_entity: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_room
    from: 'on'
    to: 'off'
    for:
      seconds: 300
  condition:
  - condition: state
    entity_id: light.bulb_17
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bulb_17
    data:
      transition: 5
