- alias: '[Security] Smoke alarm on the first floor'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_first_floor
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - repeat:
      count: 4
      sequence:
        - service: notify.pushover
          data:
            title: "Smoke Alarm"
            message: "WARNING! Smoke detected on the first floor!"
        - delay: '00:00:15'


- alias: '[Security] Smoke alarm on the second floor'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_second_floor
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - repeat:
      count: 4
      sequence:
        - service: notify.pushover
          data:
            title: "Smoke Alarm"
            message: "WARNING! Smoke detected on the second floor!"
        - delay: '00:00:15'

