- alias: '[Security] Smoke alarm on the first floor'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_1
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - repeat:
      count: 4
      sequence:
        - service: notify.pushover
          data:
            title: "Smoke Alarm"
            message: "WARNING! Smoke detected on the first floor!"
        - delay: '00:00:15'


- alias: '[Security] Tamper alarm of the Smoke1 sensor'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_1_tamper
    to: 'on'
  action:
  - service: notify.pushover
    data:
      title: "Tamper Alarm"
      message: "WARNING! Tamper alarm of the Smoke sensor 1 (first floor)"


- alias: '[Security] Smoke alarm on the second floor'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_2
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - repeat:
      count: 4
      sequence:
        - service: notify.pushover
          data:
            title: "Smoke Alarm"
            message: "WARNING! Smoke detected on the second floor!"
        - delay: '00:00:15'

