- alias: 'Smoke alarm'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.smoke_first_floor
    to: 'on'
  action:
  - service: notify.pushover
    data:
      message: "WARNING! Smoke detected!"

