
- alias: '[Stairs] Run stairs_nightlight script if motions'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_upstairs
    - binary_sensor.presence_livingroom
  action:
  - service: python_script.stairs_nightlight
    data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
      to_state: '{{ trigger.to_state.state }}'


- alias: '[Stairs] Run stairs_effects script if motions'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_upstairs
    - binary_sensor.motion_downstairs
    to: 'on'
  action:
  - service: python_script.stairs_effects
    data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
      to_state: '{{ trigger.to_state.state }}'


- alias: '[Stairs] Run stairs_effects script if no motions for 20 secs'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_upstairs
    - binary_sensor.motion_downstairs
    to: 'off'
    for:
      seconds: 20
  action:
  - service: python_script.stairs_effects
    data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
      to_state: '{{ trigger.to_state.state }}'




