
- alias: '[Stairs] Run stairs_nightlight script if motions'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.presence_upstairs
    - binary_sensor.presence_livingroom
  action:
  - service: python_script.stairs_nightlight
    data_template:
      to_state: '{{ trigger.to_state.state }}'

#===========================================================================

- alias: '[Stairs] Run stairs_effects script if motions'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.motion_upstairs
    - binary_sensor.motion_downstairs
    to: 'on'
  action:
  - service: python_script.stairs_effects
  - service: timer.start
    entity_id: timer.stairs_light_timeout


- alias: '[Stairs] Run stairs_effects when timer triggers'
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.stairs_light_timeout
  action:
  - service: python_script.stairs_effects



