- alias: '[Security] Too high temperature at the second floor'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_second_floor
    above: 40
  action:
    service: notify.pushover
    data_template:
      message: "Warning! Temperature at the second floor is {{ states.sensor.temperature_second_floor.state }} degrees"

- alias: '[Security] Too high temperature at the first floor'
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_first_floor
    above: 40
  action:
    service: notify.pushover
    data_template:
      message: "Warning! Temperature at the first floor is {{ states.sensor.temperature_first_floor.state }} degrees"
