- alias: 'Notify on unavailable wifi device'
  initial_state: true
  trigger:
    platform: state
    entity_id: light.bed_led, light.bulb_12, light.bulb_13, light.bulb_14, light.bulb_15,
               light.bulb_16, light.bulb_17, light.gateway_light_7811dcb7f720, light.light1,
               light.xiaomi_philips_desklamp, light.xiaomi_philips_desklamp_ambient_light
    to: 'unavailable'
  action:
    service: notify.pushover
    data:
      title: "Unavailable device"
      message: "The following wifi devices are not available: {% for entity_id in states.group.all_lights.attributes.entity_id %}{% set domain, device = entity_id.split('.') %}{% if states[domain][device].state == 'unavailable' %}{{ states[domain][device].attributes.friendly_name }}; {% endif %}{% endfor %}"

