- alias: '[Upstairs light] Turn on if motion (06:30 - 23:00)'
#  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.presence_upstairs
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.lightlevel_upstairs
      below: 10
    - condition: time
      after: "06:30"
      before: "22:59"
  action:
    - service: light.turn_on
      entity_id: light.ikea_lamp_1
      data:
        brightness_pct: 95
        #kelvin: 3200
        transition: 5


- alias: '[Upstairs light] Turn on if motion (23:00 - 00:00)'
#  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.presence_upstairs
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.lightlevel_upstairs
      below: 10
    - condition: time
      after: "23:00"
      before: "23:59"
  action:
    - service: light.turn_on
      entity_id: light.ikea_lamp_1
      data:
        brightness_pct: 5
        #kelvin: 2000


- alias: '[Upstairs light] Turn off in 5 minutes after motion'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_upstairs
    from: 'on'
    to: 'off'
    for:
      seconds: 300
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.ikea_lamp_1
      state: 'on'
    - condition: time
      after: "06:30"
      before: "23:59"
  action:
    - service: light.turn_off
      entity_id: light.ikea_lamp_1
      data:
        transition: 10


- alias: '[Upstairs light] Turn off (00:00 - 06:30)'
  trigger:
    platform: state
    entity_id: binary_sensor.presence_upstairs
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: light.ikea_lamp_1
      state: 'on'
    - condition: time
      after: "00:00"
      before: "06:29"
  action:
    - service: light.turn_off
      entity_id: light.ikea_lamp_1

