# Ikea switch 4

- alias: '[Upstairs] IKEA Switch light control'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_4
  action:
  - service: python_script.ikea_switch_control
    data_template:
      event: "{{ trigger.event }}"

