# Ikea switch 4

- alias: '[Upstairs] IKEA Switch light control'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_switch_4"
  action:
  - service: python_script.ikea_switch_control
    data_template:
      switch_id: ikea_switch_4
      action: '{{ trigger.payload_json.action }}'
