- alias: '[Vacation] Lights start on sunset'
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: script.turn_on
    data:
      entity_id: script.vacation_lights


- alias: '[Vacation] Lights stop at midnight'
  trigger:
  - platform: time
    at: '00:18:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: script.turn_off
    data:
      entity_id: script.vacation_lights
  - service: light.turn_off
    entity_id: light.aqara_lamp_1
  - service: light.turn_off
    entity_id: light.ikea_lamp_2
  - service: light.turn_off
    entity_id: light.kitchen_1
  - service: light.turn_off
    entity_id: light.kitchen_2
  - service: light.turn_off
    entity_id: light.gledopto_lamp_1
  - service: light.turn_off
    entity_id: light.gledopto_lamp_2
  - service: light.turn_off
    entity_id: light.gledopto_lamp_3
  - service: light.turn_off
    entity_id: light.gledopto_lamp_4
  - service: light.turn_off
    entity_id: light.ikea_lamp_13

