- alias: '[Vacation] Lights start on sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    offset: '-00:05:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: script.turn_on
    data:
      entity_id: script.vacation_lights


- alias: '[Vacation] Lights stop at midnight'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: time
    at: '00:18:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: script.turn_off
    data:
      entity_id: script.vacation_lights
  - service: light.turn_off
    data:
      entity_id: group.all_lights
  - service: light.turn_on
    entity_id: light.mood_lamp
    data:
      effect: "Chaos"

