- alias: '[System] Warning Sound RPi Speaker'
  hide_entity: true
  initial_state: false
  trigger:
  - platform: time_pattern
    seconds: "/2"
  action:
  - service: shell_command.warning_sound_rpi_speaker


- alias: '[Keypad] Stop warning signal with code 0000'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'alarm/keypad/code'
    payload: '0000'
  action:
  - service: automation.turn_off
    entity_id: automation.system_warning_sound_rpi_speaker
