- alias: 'Water leakage floor 1'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.water_first_floor
    to: 'on'
  action:
  - service: notify.pushover
    data:
      message: "WARNING! A water leakage is detected on the first floor"


- alias: 'Water leakage floor 2'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.water_second_floor
    to: 'on'
  action:
  - service: notify.pushover
    data:
      message: "WARNING! A water leakage is detected on the second floor"
