- alias: '[Security] Water leakage floor 1'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.water_first_floor
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the first floor"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the first floor"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the first floor"


- alias: '[Security] Water leakage floor 2'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.water_second_floor
    to: 'on'
  action:
  - service: automation.turn_on
    entity_id: automation.system_warning_sound_rpi_speaker
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the second floor"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the second floor"
  - delay: '00:00:10'
  - service: notify.pushover
    data:
      title: "Water leak!"
      message: "WARNING! A water leakage is detected on the second floor"


