- alias: '[Weather] Notify about weather warnings'
  trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    from: 'off'
  action:
  - service: notify.pushover
    data_template:
      title: "{{ state_attr('binary_sensor.meteoalarm', 'headline') }}"
      message: "{{ state_attr('binary_sensor.meteoalarm', 
'description')}} is effective on {{ state_attr('binary_sensor.meteoalarm', 'effective') }}.
{{ state_attr('binary_sensor.meteoalarm', 'consequences') }}. {{ state_attr('binary_sensor.meteoalarm', 'instruction') }}."
