- alias: '[WiFi Control] Notify if unavailable'
  initial_state: false
  trigger:
  - platform: state
    entity_id: light.bed_led, light.bulb_13, light.xiaomi_philips_desklamp
    to: 'unavailable'
    for:
      seconds: 15
  action:
  - service: notify.pushover
    data:
      title: "Unavailable device"
      message: "The following wifi devices are not available: {% for entity_id in states.group.wifi_lights.attributes.entity_id %}{% set domain, device = entity_id.split('.') %}{% if states[domain][device].state == 'unavailable' %}{{ states[domain][device].attributes.friendly_name }}; {% endif %}{% endfor %}"

- alias: '[WiFi Control] Run wifi problem script if unavailable'
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.bed_led, light.bulb_13, light.xiaomi_philips_desklamp
    to: 'unavailable'
    for:
      seconds: 15
  action:
  - service: python_script.wifi_problem


- alias: '[WiFi Control] Run wifi problem script if a device becomes available'
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.bed_led, light.bulb_13, light.xiaomi_philips_desklamp
    from: 'unavailable'
  action:
  - service: python_script.wifi_problem


- alias: "[WiFi Control] Run wifi problem script on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: python_script.wifi_problem


- alias: "[WiFi Control] Restart router if too many unavailable"
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.wifi_problem
    to: 'on'
    for:
      seconds: 45
  action:
  - service: notify.pushover
    data:
      title: "Warning"
      message: "Too many unavailable WiFi devices. Restart the router."
  - service: shell_command.router_restart


