- alias: '[Workroom] Flash if motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_bedroom, binary_sensor.presence_upstairs
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.ikea_lamp_13
      flash: short


- alias: '[Workroom] IKEA Switch light control'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_switch_6
  action:
  - service: python_script.ikea_switch_control
    data_template:
      event: "{{ trigger.event }}"


- alias: '[Workroom] Turn on light with Xiaomi button '
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_workroom 
      event: 1002
  condition:
  - condition: state
    entity_id: light.ikea_lamp_13
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.ikea_lamp_13
      color_temp: 400
      brightness: 255


- alias: '[Workroom] Turn off light with Xiaomi button '
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_workroom 
      event: 1002
  condition:
  - condition: state
    entity_id: light.ikea_lamp_13
    state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.ikea_lamp_13
