- alias: '[Work room] Toggle light'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2002
  action:
  - service: light.toggle
    data:
      entity_id: light.aqara_lamp_1
      color_temp: 250

- alias: '[Workroom] Flash if motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_bedroom
    entity_id: binary_sensor.presence_upstairs
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.aqara_lamp_1
      flash: short
