- alias: '[Workroom Blinds] Request position after restart'
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: '00:00:30'
  - service: mqtt.publish
    data_template:
      topic: 'zigbee2mqtt/blinds_workroom/get'
      payload: '{"position":""}'
      retain: false
      qos: 0


- alias: '[Workroom Blinds] Switch automation'
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_on_off_switch_1"
  action:
  - choose:

    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ trigger.payload_json.action == 'on' }}"
        - condition: template
          value_template: "{{ trigger.payload_json.action == 'brightness_move_up' }}"
      sequence:
      - service: cover.open_cover
        data:
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ trigger.payload_json.action == 'off' }}"
        - condition: template
          value_template: "{{ trigger.payload_json.action == 'brightness_move_down' }}"
      sequence:
      - service: cover.close_cover
        data:
          entity_id: cover.blinds_workroom

    - conditions:
      - condition: template
        value_template: "{{ trigger.payload_json.action == 'brightness_stop' }}"
      sequence:
      - service: cover.stop_cover
        data:
          entity_id: cover.blinds_workroom


