- alias: "[Workroom Blinds] Run script on start"
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom

# ------------------

- alias: "[Workroom Blinds] Set moving sensor to 0 when it's down"
  trigger:
  - platform: numeric_state
    entity_id: cover.blinds_workroom
    value_template: "{{ state.attributes.current_position }}"
    below: 39 # 36 is min
    for:
      seconds: 1
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'


- alias: "[Workroom Blinds] Set moving sensor to 0 when it's up"
  trigger:
  - platform: numeric_state
    entity_id: cover.blinds_workroom
    value_template: "{{ state.attributes.current_position }}"
    above: 97 # 100 is max
    for:
      seconds: 1
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'

# ------------------

- alias: '[Workroom Blinds] Go up'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 1002
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'off'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'on'
  - service: cover.set_cover_position
    data:
      entity_id: cover.blinds_workroom
      position: 100


- alias: '[Workroom Blinds] Stop going up'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 1002
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_workroom

# ------------------

- alias: '[Workroom Blinds] Go down'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2002
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'off'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'on'
  - service: cover.set_cover_position
    data:
      entity_id: cover.blinds_workroom
      position: 36


- alias: '[Workroom Blinds] Stop going down'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2002
  condition:
    - condition: state
      entity_id: binary_sensor.blinds_workroom_moving
      state: 'on'
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_workroom

# ------------------

- alias: '[Workroom Blinds] Go up while holding'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 1001
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'on'
  - service: cover.open_cover
    data:
      entity_id: cover.blinds_workroom


- alias: '[Workroom Blinds] Stop going up on release'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 1003
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_workroom

# ------------------
#
- alias: '[Workroom Blinds] Go down while holding'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2001
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'on'
  - service: cover.close_cover
    data:
      entity_id: cover.blinds_workroom


- alias: '[Workroom Blinds] Stop going down on release'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2003
  action:
  - service: python_script.blinds_moving_control
    data:
      entity_id: cover.blinds_workroom
      is_moving: 'off'
  - service: cover.stop_cover
    data:
      entity_id: cover.blinds_workroom

