- alias: 'Toggle light in the work room'
  initial_state: true
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: xiaomi_switch_workroom 
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.bulb_15

