- alias: '[Work room] Toggle light'
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: ikea_on_off_switch_1
      event: 2002
  action:
  - service: light.toggle
    data:
      entity_id: light.aqara_lamp_1
      color_temp: 250

