- alias: '[Workroom] Flash if motion'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_bedroom, binary_sensor.presence_upstairs
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.ikea_lamp_13
      flash: short

#-------------------------------------

- alias: '[Workroom] IKEA Switch light control'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/ikea_switch_6"
  action:
  - service: python_script.ikea_switch_control
    data_template:
      switch_id: ikea_switch_6
      action: '{{ trigger.payload_json.action }}'

