- alias: 'Toggle light in the work room'
  initial_state: true
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00028c93bf
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.bulb_15

