- alias: 'Turn on christmas lights when disarmed'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    to: 'disarmed'
  condition:
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    entity_id: light.christmas_lights


- alias: '[Vacation] Christmas lights are on at sunset'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    offset: '+00:00:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: light.turn_on
    entity_id: light.christmas_lights

- alias: '[Vacation] Christmas lights are off at sunrise'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: sun
    event: sunrise
    offset: '+00:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'on'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: light.turn_off
    entity_id: light.christmas_lights
