- alias: '[Yard] Turn on the backyard light at sunset'
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_10
    data:
      transition: 30
      brightness_pct: 95


- alias: '[Yard] Turn off the backyard light at sunrise'
  initial_state: true
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.ikea_lamp_10
    data:
      transition: 30

# --------------------------------------------------------------

- alias: '[Yard] Turn on living room if motion in backyard while all in bed'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.living_room


- alias: '[Yard] Turn off living room in 3 minutes after motion in backyard'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    from: 'on'
    to: 'off'
    for:
      seconds: 180
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.living_room

# --------------------------------------------------------------

- alias: '[Yard] Turn on lights if motion in backyard while armed away'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  - condition: sun
    after: sunset
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_1
  - delay:
      seconds: 10
  - service: light.turn_on
    entity_id: light.living_room


- alias: '[Yard] Turn off lights in 3 minutes after motion in backyard'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    from: 'on'
    to: 'off'
    for:
      seconds: 180
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  action:
  - service: light.turn_off
    entity_id: light.living_room
  - delay:
      seconds: 5
  - service: light.turn_off
    entity_id: light.ikea_lamp_1

# --------------------------------------------------------------

- alias: '[Yard] Notify if motion in backyard while armed away'
  hide_entity: true
  initial_state: true
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: armed_away
  action:
  - service: notify.pushover
    data:
      title: "Backyard motion"
      message: "Motion detected in the backyard"
#TODO: Add the camera to take a snapshot or a video record
