

- alias: '[Yard] Turn on yard lights at sunset'
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.ikea_plug_2  # Power for garden lights
  - delay: "00:00:01"
  - service: light.turn_on
    entity_id: light.ikea_lamp_10  # The Backyard light
    data:
      transition: 10
      brightness_pct: 95
  - delay: "00:00:10"
  - service: light.turn_on
    entity_id: light.ikea_lamp_11  # The Porch light
    data:
      transition: 10
      brightness_pct: 100
  - delay: "00:00:10"
  - service: light.turn_on
    entity_id: light.ikea_lamp_12  # The frontyard light
    data:
      transition: 10
      brightness_pct: 100
  - delay: "00:00:10"
  - service: light.turn_on        # The storehouse decor light
    entity_id: light.frontyard_decor
  - delay: "00:00:10"
  - service: light.turn_on         # The garden lights
    data:
      entity_id: light.garden_lights_1
      transition: 10
      brightness_pct: 100
      rgb_color: [255, 255, 255]
  - delay: '00:00:10'
  - service: light.turn_on         # Turn on an effect
    data:
      entity_id: light.garden_lights_1
      effect: "RandomColorLamp"
  - service: light.turn_on
    data:
      entity_id: light.garden_power_1


- alias: '[Yard] Turn off yard lights at sunrise'
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.frontyard_decor
  - delay: "00:00:10"
  - service: light.turn_off
    entity_id: light.ikea_lamp_12
    data:
      transition: 10
  - delay: "00:00:10"
  - service: light.turn_off
    entity_id: light.ikea_lamp_11
    data:
      transition: 10
  - delay: "00:00:10"
  - service: light.turn_off
    entity_id: light.ikea_lamp_10
    data:
      transition: 10
  - delay: "00:00:10"
  - service: light.turn_off
    entity_id: light.garden_lights_1
  - delay: '00:00:10'
  - service: switch.turn_off
    entity_id: switch.ikea_plug_2
  - delay: '00:00:10'
  - service: light.turn_off
    entity_id: light.garden_power_1

#=============================( Frontyard )================================#

- alias: '[Front Yard] Bright Light if motion after sunset'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: light.turn_on
    entity_id: light.frontyard_bright


- alias: '[Front Yard] Bright light off if no motion for 1 min'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_frontyard
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: state
    entity_id: light.frontyard_bright
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.frontyard_bright


- alias: '[Front Yard] Video if motion while armed away'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_3
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam3_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40 #TODO: shall be configurable
  - delay:
      seconds: 40


- alias: '[Front Yard] Notify if motion while armed away'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_3
      filename: '/tmp/foscam3.jpg'
  - service: notify.pushover_file
    data:
      title: "Frontyard motion"
      message: "Motion detected in the frontyard"
      data:
        file:
          path: '/tmp/foscam3.jpg'

# ---

- alias: '[Front Yard] Video if motion while all in bed'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_3
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam3_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40
  - delay:
      seconds: 40


- alias: '[Front Yard] Notify if motion while all in bed'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_3
      filename: '/tmp/foscam3.jpg'
  - service: notify.pushover_file
    data:
      title: "Frontyard motion"
      message: "Motion detected in the frontyard"
      data:
        file:
          path: '/tmp/foscam3.jpg'

# ---

- alias: '[Front Yard] Notify if motion after sunset'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: binary_sensor.openclose_livingroom
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_entrance
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_kitchen
    state: 'off'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_3
      filename: '/tmp/foscam3.jpg'
  - service: notify.pushover_file
    data:
      title: "Frontyard motion"
      message: "Motion detected in the frontyard"
      data:
        file:
          path: '/tmp/foscam3.jpg'


- alias: '[Front Yard] Video if motion after sunset'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_frontyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: binary_sensor.openclose_livingroom
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_entrance
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_kitchen
    state: 'off'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_3
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam3_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40
  - delay:
      seconds: 40


#=============================( Backyard )================================#
# Lights in the living room
#

- alias: '[Yard] Turn on living room if motion in backyard while all in bed'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.living_room


- alias: '[Yard] Turn off living room in 3 minutes after motion in backyard'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    from: 'on'
    to: 'off'
    for:
      seconds: 180
  condition:
  - condition: state
    entity_id: light.living_room
    state: 'on'
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.living_room


- alias: '[Yard] Turn on lights if motion in backyard while armed away'
  trigger:
  - platform: state 
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: light.turn_on
    entity_id: light.aqara_lamp_1
  - delay:
      seconds: 10
  - service: light.turn_on
    entity_id: light.living_room


- alias: '[Yard] Turn off lights in 3 minutes after motion in backyard'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    from: 'on'
    to: 'off'
    for:
      seconds: 180
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: light.turn_off
    entity_id: light.living_room
  - delay:
      seconds: 5
  - service: light.turn_off
    entity_id: light.aqara_lamp_1


#-----------------#

- alias: '[Yard] Notify if motion in backyard while armed away'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_1
      filename: '/tmp/foscam1.jpg'
  - service: notify.pushover_file
    data:
      title: "Backyard motion"
      message: "Motion detected in the backyard"
      data:
        file:
          path: '/tmp/foscam1.jpg'


- alias: '[Yard] Video if motion in backyard while armed away'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_1
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam1_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40
  - delay:
      seconds: 40

# ---

- alias: '[Yard] Video if motion in backyard while all in bed'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_1
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam1_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40
  - delay:
      seconds: 40


- alias: '[Yard] Notify if motion in backyard while all in bed'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'on'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_1
      filename: '/tmp/foscam1.jpg'
  - service: notify.pushover_file
    data:
      title: "Backyard motion"
      message: "Motion detected in the backyard"
      data:
        file:
          path: '/tmp/foscam1.jpg'

# ---

- alias: '[Yard] Notify if motion in backyard after sunset'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: binary_sensor.openclose_livingroom
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_entrance
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_kitchen
    state: 'off'
  action:
  - service: camera.snapshot
    data_template:
      entity_id: camera.foscam_1
      filename: '/tmp/foscam1.jpg'
  - service: notify.pushover_file
    data:
      title: "Backyard motion"
      message: "Motion detected in the backyard"
      data:
        file:
          path: '/tmp/foscam1.jpg'


- alias: '[Yard] Video if motion in backyard after sunset'
  trigger:
  - platform: state
    entity_id: binary_sensor.presence_backyard
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.all_in_bed
    state: 'off'
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'disarmed'
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: binary_sensor.openclose_livingroom
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_entrance
    state: 'off'
  - condition: state
    entity_id: binary_sensor.openclose_kitchen
    state: 'off'
  action:
  - service: camera.record
    data_template:
      entity_id: camera.foscam_1
      filename: '/home/homeassistant/.homeassistant/www/camera_records/Foscam1_{{ now().strftime("%Y%m%d-%H%M%S") }}.mp4'
      duration: 40
  - delay:
      seconds: 40

#=============================(Garden Power Supply)================================#


- alias: '[Garden Lights] Turn off garden power supply if too warm'
  trigger:
  - platform: numeric_state
    entity_id: sensor.garden_light_temperature
    above: 45
    for: '00:01:00'
  action:
  - service: switch.turn_off
    entity_id: switch.ikea_plug_2
  - service: notify.pushover
    data:
      message: "The garden power supply is turned off due to a risk of overheating."


- alias: '[Garden Lights] Fan slider'
  trigger:
  - platform: state 
    entity_id: input_number.garden_powersupply_fan
  action:
  - service: mqtt.publish
    data_template:
      topic: 'light/garden/fan'
      payload: "{{ trigger.to_state.state | int }}"
      retain: false
      qos: 0

