- alias: '[Yard] Turn on the backyard light at sunset'
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: light.turn_on
    entity_id: light.ikea_lamp_10


- alias: '[Yard] Turn off the backyard light at sunrise'
  initial_state: true
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: light.turn_off
    entity_id: light.ikea_lamp_10
