automation:
  - alias: 'Alarm Sound RPi Speaker'
    #hide_entity: true
    initial_state: False
    trigger:
      - platform: time
        seconds: "/1"
    action:
      service: shell_command.alarm_sound

shell_command:
  alarm_sound: "/usr/bin/play /home/homeassistant/.homeassistant/media/alarm.wav"

